// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SI24004.Models;

public partial class Drawing
{
    public Guid Id { get; set; }

    public string DrawingCode { get; set; }

    public string DrawingName { get; set; }

    public Guid ListItemId { get; set; }

    public virtual ICollection<DwRequest> DwRequests { get; set; } = new List<DwRequest>();

    public virtual ListItem ListItem { get; set; }
}