// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SI24004.Models;

public partial class ListItem
{
    public Guid Id { get; set; }

    public string ListItemName { get; set; }

    public string ListItemCode { get; set; }

    public virtual ICollection<Drawing> Drawings { get; set; } = new List<Drawing>();

    public virtual ICollection<Objective> Objectives { get; set; } = new List<Objective>();

    public virtual ICollection<Section> Sections { get; set; } = new List<Section>();

    public virtual ICollection<Shift> Shifts { get; set; } = new List<Shift>();

    public virtual ICollection<Status> Statuses { get; set; } = new List<Status>();
}