// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SI24004.Models;

public partial class RegularSubstand
{
    public Guid Id { get; set; }

    public string SubstanceChemical { get; set; }

    public string SubstanceIdentifier { get; set; }

    public string SubstanceCasNo { get; set; }

    public string SubstanceThresholdLimit { get; set; }

    public string SubstanceScope { get; set; }

    public string SubstanceExamples { get; set; }

    public string SubstanceReferences { get; set; }
}