// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SI24004.Models;

public partial class sqlServerContext : DbContext
{
    public sqlServerContext(DbContextOptions<sqlServerContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Th100Record> Th100Records { get; set; }

    public virtual DbSet<ThRecord> ThRecords { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("Thai_CI_AS");

        modelBuilder.Entity<Th100Record>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("TH100_RECORD");

            entity.Property(e => e.DateProcess)
                .HasColumnType("datetime")
                .HasColumnName("dateProcess");
            entity.Property(e => e.Hostname).HasMaxLength(20);
            entity.Property(e => e.ImobileLot)
                .HasMaxLength(50)
                .HasColumnName("imobileLot");
            entity.Property(e => e.ImobileSize)
                .HasMaxLength(50)
                .HasColumnName("imobileSize");
            entity.Property(e => e.ImobileType)
                .HasMaxLength(50)
                .HasColumnName("imobileType");
            entity.Property(e => e.Ipaddress)
                .HasMaxLength(20)
                .HasColumnName("IPAddress");
            entity.Property(e => e.LaserMc)
                .HasMaxLength(2)
                .HasColumnName("LaserMC");
            entity.Property(e => e.LotId)
                .ValueGeneratedOnAdd()
                .HasColumnName("lot_id");
            entity.Property(e => e.LotPo)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("lot_po");
            entity.Property(e => e.McPo)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("mc_po");
            entity.Property(e => e.McType)
                .HasMaxLength(50)
                .HasColumnName("mc_type");
            entity.Property(e => e.MemberId)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("member_id");
            entity.Property(e => e.NoPo)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("no_po");
            entity.Property(e => e.Process)
                .HasMaxLength(50)
                .HasColumnName("process");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("status");
            entity.Property(e => e.Th01)
                .HasMaxLength(10)
                .HasColumnName("th_01");
            entity.Property(e => e.Th02)
                .HasMaxLength(10)
                .HasColumnName("th_02");
            entity.Property(e => e.Th03)
                .HasMaxLength(10)
                .HasColumnName("th_03");
            entity.Property(e => e.Th04)
                .HasMaxLength(10)
                .HasColumnName("th_04");
            entity.Property(e => e.Th05)
                .HasMaxLength(10)
                .HasColumnName("th_05");
            entity.Property(e => e.Th06)
                .HasMaxLength(10)
                .HasColumnName("th_06");
            entity.Property(e => e.Th07)
                .HasMaxLength(10)
                .HasColumnName("th_07");
            entity.Property(e => e.Th08)
                .HasMaxLength(10)
                .HasColumnName("th_08");
            entity.Property(e => e.Th09)
                .HasMaxLength(10)
                .HasColumnName("th_09");
            entity.Property(e => e.Th10)
                .HasMaxLength(10)
                .HasColumnName("th_10");
            entity.Property(e => e.Th100)
                .HasMaxLength(10)
                .HasColumnName("th_100");
            entity.Property(e => e.Th101)
                .HasMaxLength(10)
                .HasColumnName("th_101");
            entity.Property(e => e.Th102)
                .HasMaxLength(10)
                .HasColumnName("th_102");
            entity.Property(e => e.Th103)
                .HasMaxLength(10)
                .HasColumnName("th_103");
            entity.Property(e => e.Th104)
                .HasMaxLength(10)
                .HasColumnName("th_104");
            entity.Property(e => e.Th105)
                .HasMaxLength(10)
                .HasColumnName("th_105");
            entity.Property(e => e.Th106)
                .HasMaxLength(10)
                .HasColumnName("th_106");
            entity.Property(e => e.Th107)
                .HasMaxLength(10)
                .HasColumnName("th_107");
            entity.Property(e => e.Th108)
                .HasMaxLength(10)
                .HasColumnName("th_108");
            entity.Property(e => e.Th109)
                .HasMaxLength(10)
                .HasColumnName("th_109");
            entity.Property(e => e.Th11)
                .HasMaxLength(10)
                .HasColumnName("th_11");
            entity.Property(e => e.Th110)
                .HasMaxLength(10)
                .HasColumnName("th_110");
            entity.Property(e => e.Th111)
                .HasMaxLength(10)
                .HasColumnName("th_111");
            entity.Property(e => e.Th112)
                .HasMaxLength(10)
                .HasColumnName("th_112");
            entity.Property(e => e.Th113)
                .HasMaxLength(10)
                .HasColumnName("th_113");
            entity.Property(e => e.Th114)
                .HasMaxLength(10)
                .HasColumnName("th_114");
            entity.Property(e => e.Th115)
                .HasMaxLength(10)
                .HasColumnName("th_115");
            entity.Property(e => e.Th116)
                .HasMaxLength(10)
                .HasColumnName("th_116");
            entity.Property(e => e.Th117)
                .HasMaxLength(10)
                .HasColumnName("th_117");
            entity.Property(e => e.Th118)
                .HasMaxLength(10)
                .HasColumnName("th_118");
            entity.Property(e => e.Th119)
                .HasMaxLength(10)
                .HasColumnName("th_119");
            entity.Property(e => e.Th12)
                .HasMaxLength(10)
                .HasColumnName("th_12");
            entity.Property(e => e.Th120)
                .HasMaxLength(10)
                .HasColumnName("th_120");
            entity.Property(e => e.Th121)
                .HasMaxLength(10)
                .HasColumnName("th_121");
            entity.Property(e => e.Th122)
                .HasMaxLength(10)
                .HasColumnName("th_122");
            entity.Property(e => e.Th123)
                .HasMaxLength(10)
                .HasColumnName("th_123");
            entity.Property(e => e.Th124)
                .HasMaxLength(10)
                .HasColumnName("th_124");
            entity.Property(e => e.Th125)
                .HasMaxLength(10)
                .HasColumnName("th_125");
            entity.Property(e => e.Th126)
                .HasMaxLength(10)
                .HasColumnName("th_126");
            entity.Property(e => e.Th127)
                .HasMaxLength(10)
                .HasColumnName("th_127");
            entity.Property(e => e.Th128)
                .HasMaxLength(10)
                .HasColumnName("th_128");
            entity.Property(e => e.Th129)
                .HasMaxLength(10)
                .HasColumnName("th_129");
            entity.Property(e => e.Th13)
                .HasMaxLength(10)
                .HasColumnName("th_13");
            entity.Property(e => e.Th130)
                .HasMaxLength(10)
                .HasColumnName("th_130");
            entity.Property(e => e.Th131)
                .HasMaxLength(10)
                .HasColumnName("th_131");
            entity.Property(e => e.Th132)
                .HasMaxLength(10)
                .HasColumnName("th_132");
            entity.Property(e => e.Th133)
                .HasMaxLength(10)
                .HasColumnName("th_133");
            entity.Property(e => e.Th134)
                .HasMaxLength(10)
                .HasColumnName("th_134");
            entity.Property(e => e.Th135)
                .HasMaxLength(10)
                .HasColumnName("th_135");
            entity.Property(e => e.Th136)
                .HasMaxLength(10)
                .HasColumnName("th_136");
            entity.Property(e => e.Th137)
                .HasMaxLength(10)
                .HasColumnName("th_137");
            entity.Property(e => e.Th138)
                .HasMaxLength(10)
                .HasColumnName("th_138");
            entity.Property(e => e.Th139)
                .HasMaxLength(10)
                .HasColumnName("th_139");
            entity.Property(e => e.Th14)
                .HasMaxLength(10)
                .HasColumnName("th_14");
            entity.Property(e => e.Th140)
                .HasMaxLength(10)
                .HasColumnName("th_140");
            entity.Property(e => e.Th141)
                .HasMaxLength(10)
                .HasColumnName("th_141");
            entity.Property(e => e.Th142)
                .HasMaxLength(10)
                .HasColumnName("th_142");
            entity.Property(e => e.Th143)
                .HasMaxLength(10)
                .HasColumnName("th_143");
            entity.Property(e => e.Th144)
                .HasMaxLength(10)
                .HasColumnName("th_144");
            entity.Property(e => e.Th145)
                .HasMaxLength(10)
                .HasColumnName("th_145");
            entity.Property(e => e.Th146)
                .HasMaxLength(10)
                .HasColumnName("th_146");
            entity.Property(e => e.Th147)
                .HasMaxLength(10)
                .HasColumnName("th_147");
            entity.Property(e => e.Th148)
                .HasMaxLength(10)
                .HasColumnName("th_148");
            entity.Property(e => e.Th149)
                .HasMaxLength(10)
                .HasColumnName("th_149");
            entity.Property(e => e.Th15)
                .HasMaxLength(10)
                .HasColumnName("th_15");
            entity.Property(e => e.Th150)
                .HasMaxLength(10)
                .HasColumnName("th_150");
            entity.Property(e => e.Th151)
                .HasMaxLength(10)
                .HasColumnName("th_151");
            entity.Property(e => e.Th152)
                .HasMaxLength(10)
                .HasColumnName("th_152");
            entity.Property(e => e.Th153)
                .HasMaxLength(10)
                .HasColumnName("th_153");
            entity.Property(e => e.Th154)
                .HasMaxLength(10)
                .HasColumnName("th_154");
            entity.Property(e => e.Th155)
                .HasMaxLength(10)
                .HasColumnName("th_155");
            entity.Property(e => e.Th156)
                .HasMaxLength(10)
                .HasColumnName("th_156");
            entity.Property(e => e.Th157)
                .HasMaxLength(10)
                .HasColumnName("th_157");
            entity.Property(e => e.Th158)
                .HasMaxLength(10)
                .HasColumnName("th_158");
            entity.Property(e => e.Th159)
                .HasMaxLength(10)
                .HasColumnName("th_159");
            entity.Property(e => e.Th16)
                .HasMaxLength(10)
                .HasColumnName("th_16");
            entity.Property(e => e.Th160)
                .HasMaxLength(10)
                .HasColumnName("th_160");
            entity.Property(e => e.Th161)
                .HasMaxLength(10)
                .HasColumnName("th_161");
            entity.Property(e => e.Th162)
                .HasMaxLength(10)
                .HasColumnName("th_162");
            entity.Property(e => e.Th163)
                .HasMaxLength(10)
                .HasColumnName("th_163");
            entity.Property(e => e.Th164)
                .HasMaxLength(10)
                .HasColumnName("th_164");
            entity.Property(e => e.Th165)
                .HasMaxLength(10)
                .HasColumnName("th_165");
            entity.Property(e => e.Th166)
                .HasMaxLength(10)
                .HasColumnName("th_166");
            entity.Property(e => e.Th167)
                .HasMaxLength(10)
                .HasColumnName("th_167");
            entity.Property(e => e.Th168)
                .HasMaxLength(10)
                .HasColumnName("th_168");
            entity.Property(e => e.Th169)
                .HasMaxLength(10)
                .HasColumnName("th_169");
            entity.Property(e => e.Th17)
                .HasMaxLength(10)
                .HasColumnName("th_17");
            entity.Property(e => e.Th170)
                .HasMaxLength(10)
                .HasColumnName("th_170");
            entity.Property(e => e.Th171)
                .HasMaxLength(10)
                .HasColumnName("th_171");
            entity.Property(e => e.Th172)
                .HasMaxLength(10)
                .HasColumnName("th_172");
            entity.Property(e => e.Th173)
                .HasMaxLength(10)
                .HasColumnName("th_173");
            entity.Property(e => e.Th174)
                .HasMaxLength(10)
                .HasColumnName("th_174");
            entity.Property(e => e.Th175)
                .HasMaxLength(10)
                .HasColumnName("th_175");
            entity.Property(e => e.Th176)
                .HasMaxLength(10)
                .HasColumnName("th_176");
            entity.Property(e => e.Th177)
                .HasMaxLength(10)
                .HasColumnName("th_177");
            entity.Property(e => e.Th178)
                .HasMaxLength(10)
                .HasColumnName("th_178");
            entity.Property(e => e.Th179)
                .HasMaxLength(10)
                .HasColumnName("th_179");
            entity.Property(e => e.Th18)
                .HasMaxLength(10)
                .HasColumnName("th_18");
            entity.Property(e => e.Th180)
                .HasMaxLength(10)
                .HasColumnName("th_180");
            entity.Property(e => e.Th181)
                .HasMaxLength(10)
                .HasColumnName("th_181");
            entity.Property(e => e.Th182)
                .HasMaxLength(10)
                .HasColumnName("th_182");
            entity.Property(e => e.Th183)
                .HasMaxLength(10)
                .HasColumnName("th_183");
            entity.Property(e => e.Th184)
                .HasMaxLength(10)
                .HasColumnName("th_184");
            entity.Property(e => e.Th185)
                .HasMaxLength(10)
                .HasColumnName("th_185");
            entity.Property(e => e.Th186)
                .HasMaxLength(10)
                .HasColumnName("th_186");
            entity.Property(e => e.Th187)
                .HasMaxLength(10)
                .HasColumnName("th_187");
            entity.Property(e => e.Th188)
                .HasMaxLength(10)
                .HasColumnName("th_188");
            entity.Property(e => e.Th189)
                .HasMaxLength(10)
                .HasColumnName("th_189");
            entity.Property(e => e.Th19)
                .HasMaxLength(10)
                .HasColumnName("th_19");
            entity.Property(e => e.Th190)
                .HasMaxLength(10)
                .HasColumnName("th_190");
            entity.Property(e => e.Th191)
                .HasMaxLength(10)
                .HasColumnName("th_191");
            entity.Property(e => e.Th192)
                .HasMaxLength(10)
                .HasColumnName("th_192");
            entity.Property(e => e.Th193)
                .HasMaxLength(10)
                .HasColumnName("th_193");
            entity.Property(e => e.Th194)
                .HasMaxLength(10)
                .HasColumnName("th_194");
            entity.Property(e => e.Th195)
                .HasMaxLength(10)
                .HasColumnName("th_195");
            entity.Property(e => e.Th196)
                .HasMaxLength(10)
                .HasColumnName("th_196");
            entity.Property(e => e.Th197)
                .HasMaxLength(10)
                .HasColumnName("th_197");
            entity.Property(e => e.Th198)
                .HasMaxLength(10)
                .HasColumnName("th_198");
            entity.Property(e => e.Th199)
                .HasMaxLength(10)
                .HasColumnName("th_199");
            entity.Property(e => e.Th20)
                .HasMaxLength(10)
                .HasColumnName("th_20");
            entity.Property(e => e.Th200)
                .HasMaxLength(10)
                .HasColumnName("th_200");
            entity.Property(e => e.Th201)
                .HasMaxLength(10)
                .HasColumnName("th_201");
            entity.Property(e => e.Th202)
                .HasMaxLength(10)
                .HasColumnName("th_202");
            entity.Property(e => e.Th203)
                .HasMaxLength(10)
                .HasColumnName("th_203");
            entity.Property(e => e.Th204)
                .HasMaxLength(10)
                .HasColumnName("th_204");
            entity.Property(e => e.Th205)
                .HasMaxLength(10)
                .HasColumnName("th_205");
            entity.Property(e => e.Th206)
                .HasMaxLength(10)
                .HasColumnName("th_206");
            entity.Property(e => e.Th207)
                .HasMaxLength(10)
                .HasColumnName("th_207");
            entity.Property(e => e.Th208)
                .HasMaxLength(10)
                .HasColumnName("th_208");
            entity.Property(e => e.Th209)
                .HasMaxLength(10)
                .HasColumnName("th_209");
            entity.Property(e => e.Th21)
                .HasMaxLength(10)
                .HasColumnName("th_21");
            entity.Property(e => e.Th210)
                .HasMaxLength(10)
                .HasColumnName("th_210");
            entity.Property(e => e.Th211)
                .HasMaxLength(10)
                .HasColumnName("th_211");
            entity.Property(e => e.Th212)
                .HasMaxLength(10)
                .HasColumnName("th_212");
            entity.Property(e => e.Th213)
                .HasMaxLength(10)
                .HasColumnName("th_213");
            entity.Property(e => e.Th214)
                .HasMaxLength(10)
                .HasColumnName("th_214");
            entity.Property(e => e.Th215)
                .HasMaxLength(10)
                .HasColumnName("th_215");
            entity.Property(e => e.Th216)
                .HasMaxLength(10)
                .HasColumnName("th_216");
            entity.Property(e => e.Th217)
                .HasMaxLength(10)
                .HasColumnName("th_217");
            entity.Property(e => e.Th218)
                .HasMaxLength(10)
                .HasColumnName("th_218");
            entity.Property(e => e.Th219)
                .HasMaxLength(10)
                .HasColumnName("th_219");
            entity.Property(e => e.Th22)
                .HasMaxLength(10)
                .HasColumnName("th_22");
            entity.Property(e => e.Th220)
                .HasMaxLength(10)
                .HasColumnName("th_220");
            entity.Property(e => e.Th221)
                .HasMaxLength(10)
                .HasColumnName("th_221");
            entity.Property(e => e.Th222)
                .HasMaxLength(10)
                .HasColumnName("th_222");
            entity.Property(e => e.Th223)
                .HasMaxLength(10)
                .HasColumnName("th_223");
            entity.Property(e => e.Th224)
                .HasMaxLength(10)
                .HasColumnName("th_224");
            entity.Property(e => e.Th225)
                .HasMaxLength(10)
                .HasColumnName("th_225");
            entity.Property(e => e.Th226)
                .HasMaxLength(10)
                .HasColumnName("th_226");
            entity.Property(e => e.Th227)
                .HasMaxLength(10)
                .HasColumnName("th_227");
            entity.Property(e => e.Th228)
                .HasMaxLength(10)
                .HasColumnName("th_228");
            entity.Property(e => e.Th229)
                .HasMaxLength(10)
                .HasColumnName("th_229");
            entity.Property(e => e.Th23)
                .HasMaxLength(10)
                .HasColumnName("th_23");
            entity.Property(e => e.Th230)
                .HasMaxLength(10)
                .HasColumnName("th_230");
            entity.Property(e => e.Th231)
                .HasMaxLength(10)
                .HasColumnName("th_231");
            entity.Property(e => e.Th232)
                .HasMaxLength(10)
                .HasColumnName("th_232");
            entity.Property(e => e.Th233)
                .HasMaxLength(10)
                .HasColumnName("th_233");
            entity.Property(e => e.Th234)
                .HasMaxLength(10)
                .HasColumnName("th_234");
            entity.Property(e => e.Th235)
                .HasMaxLength(10)
                .HasColumnName("th_235");
            entity.Property(e => e.Th236)
                .HasMaxLength(10)
                .HasColumnName("th_236");
            entity.Property(e => e.Th237)
                .HasMaxLength(10)
                .HasColumnName("th_237");
            entity.Property(e => e.Th238)
                .HasMaxLength(10)
                .HasColumnName("th_238");
            entity.Property(e => e.Th239)
                .HasMaxLength(10)
                .HasColumnName("th_239");
            entity.Property(e => e.Th24)
                .HasMaxLength(10)
                .HasColumnName("th_24");
            entity.Property(e => e.Th240)
                .HasMaxLength(10)
                .HasColumnName("th_240");
            entity.Property(e => e.Th241)
                .HasMaxLength(10)
                .HasColumnName("th_241");
            entity.Property(e => e.Th242)
                .HasMaxLength(10)
                .HasColumnName("th_242");
            entity.Property(e => e.Th243)
                .HasMaxLength(10)
                .HasColumnName("th_243");
            entity.Property(e => e.Th244)
                .HasMaxLength(10)
                .HasColumnName("th_244");
            entity.Property(e => e.Th245)
                .HasMaxLength(10)
                .HasColumnName("th_245");
            entity.Property(e => e.Th246)
                .HasMaxLength(10)
                .HasColumnName("th_246");
            entity.Property(e => e.Th247)
                .HasMaxLength(10)
                .HasColumnName("th_247");
            entity.Property(e => e.Th248)
                .HasMaxLength(10)
                .HasColumnName("th_248");
            entity.Property(e => e.Th249)
                .HasMaxLength(10)
                .HasColumnName("th_249");
            entity.Property(e => e.Th25)
                .HasMaxLength(10)
                .HasColumnName("th_25");
            entity.Property(e => e.Th250)
                .HasMaxLength(10)
                .HasColumnName("th_250");
            entity.Property(e => e.Th251)
                .HasMaxLength(50)
                .HasColumnName("th_251");
            entity.Property(e => e.Th252)
                .HasMaxLength(10)
                .HasColumnName("th_252");
            entity.Property(e => e.Th253)
                .HasMaxLength(10)
                .HasColumnName("th_253");
            entity.Property(e => e.Th254)
                .HasMaxLength(10)
                .HasColumnName("th_254");
            entity.Property(e => e.Th255)
                .HasMaxLength(10)
                .HasColumnName("th_255");
            entity.Property(e => e.Th256)
                .HasMaxLength(10)
                .HasColumnName("th_256");
            entity.Property(e => e.Th257)
                .HasMaxLength(10)
                .HasColumnName("th_257");
            entity.Property(e => e.Th258)
                .HasMaxLength(10)
                .HasColumnName("th_258");
            entity.Property(e => e.Th259)
                .HasMaxLength(10)
                .HasColumnName("th_259");
            entity.Property(e => e.Th26)
                .HasMaxLength(10)
                .HasColumnName("th_26");
            entity.Property(e => e.Th260)
                .HasMaxLength(10)
                .HasColumnName("th_260");
            entity.Property(e => e.Th261)
                .HasMaxLength(10)
                .HasColumnName("th_261");
            entity.Property(e => e.Th262)
                .HasMaxLength(10)
                .HasColumnName("th_262");
            entity.Property(e => e.Th263)
                .HasMaxLength(10)
                .HasColumnName("th_263");
            entity.Property(e => e.Th264)
                .HasMaxLength(10)
                .HasColumnName("th_264");
            entity.Property(e => e.Th265)
                .HasMaxLength(10)
                .HasColumnName("th_265");
            entity.Property(e => e.Th266)
                .HasMaxLength(10)
                .HasColumnName("th_266");
            entity.Property(e => e.Th267)
                .HasMaxLength(10)
                .HasColumnName("th_267");
            entity.Property(e => e.Th268)
                .HasMaxLength(10)
                .HasColumnName("th_268");
            entity.Property(e => e.Th269)
                .HasMaxLength(10)
                .HasColumnName("th_269");
            entity.Property(e => e.Th27)
                .HasMaxLength(10)
                .HasColumnName("th_27");
            entity.Property(e => e.Th270)
                .HasMaxLength(10)
                .HasColumnName("th_270");
            entity.Property(e => e.Th271)
                .HasMaxLength(10)
                .HasColumnName("th_271");
            entity.Property(e => e.Th272)
                .HasMaxLength(10)
                .HasColumnName("th_272");
            entity.Property(e => e.Th273)
                .HasMaxLength(10)
                .HasColumnName("th_273");
            entity.Property(e => e.Th274)
                .HasMaxLength(10)
                .HasColumnName("th_274");
            entity.Property(e => e.Th275)
                .HasMaxLength(10)
                .HasColumnName("th_275");
            entity.Property(e => e.Th276)
                .HasMaxLength(10)
                .HasColumnName("th_276");
            entity.Property(e => e.Th277)
                .HasMaxLength(10)
                .HasColumnName("th_277");
            entity.Property(e => e.Th278)
                .HasMaxLength(10)
                .HasColumnName("th_278");
            entity.Property(e => e.Th279)
                .HasMaxLength(10)
                .HasColumnName("th_279");
            entity.Property(e => e.Th28)
                .HasMaxLength(10)
                .HasColumnName("th_28");
            entity.Property(e => e.Th280)
                .HasMaxLength(10)
                .HasColumnName("th_280");
            entity.Property(e => e.Th281)
                .HasMaxLength(10)
                .HasColumnName("th_281");
            entity.Property(e => e.Th282)
                .HasMaxLength(10)
                .HasColumnName("th_282");
            entity.Property(e => e.Th283)
                .HasMaxLength(10)
                .HasColumnName("th_283");
            entity.Property(e => e.Th284)
                .HasMaxLength(10)
                .HasColumnName("th_284");
            entity.Property(e => e.Th285)
                .HasMaxLength(10)
                .HasColumnName("th_285");
            entity.Property(e => e.Th286)
                .HasMaxLength(10)
                .HasColumnName("th_286");
            entity.Property(e => e.Th287)
                .HasMaxLength(10)
                .HasColumnName("th_287");
            entity.Property(e => e.Th288)
                .HasMaxLength(10)
                .HasColumnName("th_288");
            entity.Property(e => e.Th289)
                .HasMaxLength(10)
                .HasColumnName("th_289");
            entity.Property(e => e.Th29)
                .HasMaxLength(10)
                .HasColumnName("th_29");
            entity.Property(e => e.Th290)
                .HasMaxLength(10)
                .HasColumnName("th_290");
            entity.Property(e => e.Th291)
                .HasMaxLength(10)
                .HasColumnName("th_291");
            entity.Property(e => e.Th292)
                .HasMaxLength(10)
                .HasColumnName("th_292");
            entity.Property(e => e.Th293)
                .HasMaxLength(10)
                .HasColumnName("th_293");
            entity.Property(e => e.Th294)
                .HasMaxLength(10)
                .HasColumnName("th_294");
            entity.Property(e => e.Th295)
                .HasMaxLength(10)
                .HasColumnName("th_295");
            entity.Property(e => e.Th296)
                .HasMaxLength(10)
                .HasColumnName("th_296");
            entity.Property(e => e.Th297)
                .HasMaxLength(10)
                .HasColumnName("th_297");
            entity.Property(e => e.Th298)
                .HasMaxLength(10)
                .HasColumnName("th_298");
            entity.Property(e => e.Th299)
                .HasMaxLength(10)
                .HasColumnName("th_299");
            entity.Property(e => e.Th30)
                .HasMaxLength(10)
                .HasColumnName("th_30");
            entity.Property(e => e.Th300)
                .HasMaxLength(10)
                .HasColumnName("th_300");
            entity.Property(e => e.Th31)
                .HasMaxLength(10)
                .HasColumnName("th_31");
            entity.Property(e => e.Th32)
                .HasMaxLength(10)
                .HasColumnName("th_32");
            entity.Property(e => e.Th33)
                .HasMaxLength(10)
                .HasColumnName("th_33");
            entity.Property(e => e.Th34)
                .HasMaxLength(10)
                .HasColumnName("th_34");
            entity.Property(e => e.Th35)
                .HasMaxLength(10)
                .HasColumnName("th_35");
            entity.Property(e => e.Th36)
                .HasMaxLength(10)
                .HasColumnName("th_36");
            entity.Property(e => e.Th37)
                .HasMaxLength(10)
                .HasColumnName("th_37");
            entity.Property(e => e.Th38)
                .HasMaxLength(10)
                .HasColumnName("th_38");
            entity.Property(e => e.Th39)
                .HasMaxLength(10)
                .HasColumnName("th_39");
            entity.Property(e => e.Th40)
                .HasMaxLength(10)
                .HasColumnName("th_40");
            entity.Property(e => e.Th41)
                .HasMaxLength(10)
                .HasColumnName("th_41");
            entity.Property(e => e.Th42)
                .HasMaxLength(10)
                .HasColumnName("th_42");
            entity.Property(e => e.Th43)
                .HasMaxLength(10)
                .HasColumnName("th_43");
            entity.Property(e => e.Th44)
                .HasMaxLength(10)
                .HasColumnName("th_44");
            entity.Property(e => e.Th45)
                .HasMaxLength(10)
                .HasColumnName("th_45");
            entity.Property(e => e.Th46)
                .HasMaxLength(10)
                .HasColumnName("th_46");
            entity.Property(e => e.Th47)
                .HasMaxLength(10)
                .HasColumnName("th_47");
            entity.Property(e => e.Th48)
                .HasMaxLength(10)
                .HasColumnName("th_48");
            entity.Property(e => e.Th49)
                .HasMaxLength(10)
                .HasColumnName("th_49");
            entity.Property(e => e.Th50)
                .HasMaxLength(10)
                .HasColumnName("th_50");
            entity.Property(e => e.Th51)
                .HasMaxLength(10)
                .HasColumnName("th_51");
            entity.Property(e => e.Th52)
                .HasMaxLength(10)
                .HasColumnName("th_52");
            entity.Property(e => e.Th53)
                .HasMaxLength(10)
                .HasColumnName("th_53");
            entity.Property(e => e.Th54)
                .HasMaxLength(10)
                .HasColumnName("th_54");
            entity.Property(e => e.Th55)
                .HasMaxLength(10)
                .HasColumnName("th_55");
            entity.Property(e => e.Th56)
                .HasMaxLength(10)
                .HasColumnName("th_56");
            entity.Property(e => e.Th57)
                .HasMaxLength(10)
                .HasColumnName("th_57");
            entity.Property(e => e.Th58)
                .HasMaxLength(10)
                .HasColumnName("th_58");
            entity.Property(e => e.Th59)
                .HasMaxLength(10)
                .HasColumnName("th_59");
            entity.Property(e => e.Th60)
                .HasMaxLength(10)
                .HasColumnName("th_60");
            entity.Property(e => e.Th61)
                .HasMaxLength(10)
                .HasColumnName("th_61");
            entity.Property(e => e.Th62)
                .HasMaxLength(10)
                .HasColumnName("th_62");
            entity.Property(e => e.Th63)
                .HasMaxLength(10)
                .HasColumnName("th_63");
            entity.Property(e => e.Th64)
                .HasMaxLength(10)
                .HasColumnName("th_64");
            entity.Property(e => e.Th65)
                .HasMaxLength(10)
                .HasColumnName("th_65");
            entity.Property(e => e.Th66)
                .HasMaxLength(10)
                .HasColumnName("th_66");
            entity.Property(e => e.Th67)
                .HasMaxLength(10)
                .HasColumnName("th_67");
            entity.Property(e => e.Th68)
                .HasMaxLength(10)
                .HasColumnName("th_68");
            entity.Property(e => e.Th69)
                .HasMaxLength(10)
                .HasColumnName("th_69");
            entity.Property(e => e.Th70)
                .HasMaxLength(10)
                .HasColumnName("th_70");
            entity.Property(e => e.Th71)
                .HasMaxLength(10)
                .HasColumnName("th_71");
            entity.Property(e => e.Th72)
                .HasMaxLength(10)
                .HasColumnName("th_72");
            entity.Property(e => e.Th73)
                .HasMaxLength(10)
                .HasColumnName("th_73");
            entity.Property(e => e.Th74)
                .HasMaxLength(10)
                .HasColumnName("th_74");
            entity.Property(e => e.Th75)
                .HasMaxLength(10)
                .HasColumnName("th_75");
            entity.Property(e => e.Th76)
                .HasMaxLength(10)
                .HasColumnName("th_76");
            entity.Property(e => e.Th77)
                .HasMaxLength(10)
                .HasColumnName("th_77");
            entity.Property(e => e.Th78)
                .HasMaxLength(10)
                .HasColumnName("th_78");
            entity.Property(e => e.Th79)
                .HasMaxLength(10)
                .HasColumnName("th_79");
            entity.Property(e => e.Th80)
                .HasMaxLength(10)
                .HasColumnName("th_80");
            entity.Property(e => e.Th81)
                .HasMaxLength(10)
                .HasColumnName("th_81");
            entity.Property(e => e.Th82)
                .HasMaxLength(10)
                .HasColumnName("th_82");
            entity.Property(e => e.Th83)
                .HasMaxLength(10)
                .HasColumnName("th_83");
            entity.Property(e => e.Th84)
                .HasMaxLength(10)
                .HasColumnName("th_84");
            entity.Property(e => e.Th85)
                .HasMaxLength(10)
                .HasColumnName("th_85");
            entity.Property(e => e.Th86)
                .HasMaxLength(10)
                .HasColumnName("th_86");
            entity.Property(e => e.Th87)
                .HasMaxLength(10)
                .HasColumnName("th_87");
            entity.Property(e => e.Th88)
                .HasMaxLength(10)
                .HasColumnName("th_88");
            entity.Property(e => e.Th89)
                .HasMaxLength(10)
                .HasColumnName("th_89");
            entity.Property(e => e.Th90)
                .HasMaxLength(10)
                .HasColumnName("th_90");
            entity.Property(e => e.Th91)
                .HasMaxLength(10)
                .HasColumnName("th_91");
            entity.Property(e => e.Th92)
                .HasMaxLength(10)
                .HasColumnName("th_92");
            entity.Property(e => e.Th93)
                .HasMaxLength(10)
                .HasColumnName("th_93");
            entity.Property(e => e.Th94)
                .HasMaxLength(10)
                .HasColumnName("th_94");
            entity.Property(e => e.Th95)
                .HasMaxLength(10)
                .HasColumnName("th_95");
            entity.Property(e => e.Th96)
                .HasMaxLength(10)
                .HasColumnName("th_96");
            entity.Property(e => e.Th97)
                .HasMaxLength(10)
                .HasColumnName("th_97");
            entity.Property(e => e.Th98)
                .HasMaxLength(10)
                .HasColumnName("th_98");
            entity.Property(e => e.Th99)
                .HasMaxLength(10)
                .HasColumnName("th_99");
            entity.Property(e => e.TimeProcess)
                .HasColumnType("datetime")
                .HasColumnName("timeProcess");
        });

        modelBuilder.Entity<ThRecord>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("TH_RECORD", tb => tb.HasTrigger("log_lotno_thickness"));

            entity.HasIndex(e => e.LotId, "_dta_index_TH_RECORD_14_613577224__K1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17_18_19_20_21_22_23_24_25_26_27_28_29_30_31_32_33_");

            entity.HasIndex(e => e.LotId, "_dta_index_TH_RECORD_5_613577224__K1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17_18_19_20_21_22_23_24_25_26_27_28_29_30_31_32_33_");

            entity.HasIndex(e => new { e.McPo, e.ImobileSize, e.LotPo, e.NoPo, e.LotId }, "_dta_index_TH_RECORD_5_613577224__K3_K19_K2_K4_K1_6_9_10_11_12_14_17");

            entity.HasIndex(e => e.ImobileLot, "_dta_index_TH_RECORD_c_5_613577224__K17").IsClustered();

            entity.Property(e => e.AvgTh)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("avg_th");
            entity.Property(e => e.Ca1In1)
                .HasMaxLength(10)
                .HasColumnName("ca1_in1");
            entity.Property(e => e.Ca1In10)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("ca1_in10");
            entity.Property(e => e.Ca1In2)
                .HasMaxLength(10)
                .HasColumnName("ca1_in2");
            entity.Property(e => e.Ca1In3)
                .HasMaxLength(10)
                .HasColumnName("ca1_in3");
            entity.Property(e => e.Ca1In4)
                .HasMaxLength(10)
                .HasColumnName("ca1_in4");
            entity.Property(e => e.Ca1In5)
                .HasMaxLength(10)
                .HasColumnName("ca1_in5");
            entity.Property(e => e.Ca1In6)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("ca1_in6");
            entity.Property(e => e.Ca1In7)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("ca1_in7");
            entity.Property(e => e.Ca1In8)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("ca1_in8");
            entity.Property(e => e.Ca1In9)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("ca1_in9");
            entity.Property(e => e.Ca1Out1)
                .HasMaxLength(10)
                .HasColumnName("ca1_out1");
            entity.Property(e => e.Ca1Out10)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("ca1_out10");
            entity.Property(e => e.Ca1Out2)
                .HasMaxLength(10)
                .HasColumnName("ca1_out2");
            entity.Property(e => e.Ca1Out3)
                .HasMaxLength(10)
                .HasColumnName("ca1_out3");
            entity.Property(e => e.Ca1Out4)
                .HasMaxLength(10)
                .HasColumnName("ca1_out4");
            entity.Property(e => e.Ca1Out5)
                .HasMaxLength(10)
                .HasColumnName("ca1_out5");
            entity.Property(e => e.Ca1Out6)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("ca1_out6");
            entity.Property(e => e.Ca1Out7)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("ca1_out7");
            entity.Property(e => e.Ca1Out8)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("ca1_out8");
            entity.Property(e => e.Ca1Out9)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("ca1_out9");
            entity.Property(e => e.Ca2In1)
                .HasMaxLength(10)
                .HasColumnName("ca2_in1");
            entity.Property(e => e.Ca2In10)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("ca2_in10");
            entity.Property(e => e.Ca2In2)
                .HasMaxLength(10)
                .HasColumnName("ca2_in2");
            entity.Property(e => e.Ca2In3)
                .HasMaxLength(10)
                .HasColumnName("ca2_in3");
            entity.Property(e => e.Ca2In4)
                .HasMaxLength(10)
                .HasColumnName("ca2_in4");
            entity.Property(e => e.Ca2In5)
                .HasMaxLength(10)
                .HasColumnName("ca2_in5");
            entity.Property(e => e.Ca2In6)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("ca2_in6");
            entity.Property(e => e.Ca2In7)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("ca2_in7");
            entity.Property(e => e.Ca2In8)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("ca2_in8");
            entity.Property(e => e.Ca2In9)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("ca2_in9");
            entity.Property(e => e.Ca2Out1)
                .HasMaxLength(10)
                .HasColumnName("ca2_out1");
            entity.Property(e => e.Ca2Out2)
                .HasMaxLength(10)
                .HasColumnName("ca2_out2");
            entity.Property(e => e.Ca2Out3)
                .HasMaxLength(10)
                .HasColumnName("ca2_out3");
            entity.Property(e => e.Ca2Out4)
                .HasMaxLength(10)
                .HasColumnName("ca2_out4");
            entity.Property(e => e.Ca2Out5)
                .HasMaxLength(10)
                .HasColumnName("ca2_out5");
            entity.Property(e => e.Ca3In1)
                .HasMaxLength(10)
                .HasColumnName("ca3_in1");
            entity.Property(e => e.Ca3In10)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("ca3_in10");
            entity.Property(e => e.Ca3In2)
                .HasMaxLength(10)
                .HasColumnName("ca3_in2");
            entity.Property(e => e.Ca3In3)
                .HasMaxLength(10)
                .HasColumnName("ca3_in3");
            entity.Property(e => e.Ca3In4)
                .HasMaxLength(10)
                .HasColumnName("ca3_in4");
            entity.Property(e => e.Ca3In5)
                .HasMaxLength(10)
                .HasColumnName("ca3_in5");
            entity.Property(e => e.Ca3In6)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("ca3_in6");
            entity.Property(e => e.Ca3In7)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("ca3_in7");
            entity.Property(e => e.Ca3In8)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("ca3_in8");
            entity.Property(e => e.Ca3In9)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("ca3_in9");
            entity.Property(e => e.Ca3Out1)
                .HasMaxLength(10)
                .HasColumnName("ca3_out1");
            entity.Property(e => e.Ca3Out2)
                .HasMaxLength(10)
                .HasColumnName("ca3_out2");
            entity.Property(e => e.Ca3Out3)
                .HasMaxLength(10)
                .HasColumnName("ca3_out3");
            entity.Property(e => e.Ca3Out4)
                .HasMaxLength(10)
                .HasColumnName("ca3_out4");
            entity.Property(e => e.Ca3Out5)
                .HasMaxLength(10)
                .HasColumnName("ca3_out5");
            entity.Property(e => e.Ca4In1)
                .HasMaxLength(10)
                .HasColumnName("ca4_in1");
            entity.Property(e => e.Ca4In10)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("ca4_in10");
            entity.Property(e => e.Ca4In2)
                .HasMaxLength(10)
                .HasColumnName("ca4_in2");
            entity.Property(e => e.Ca4In3)
                .HasMaxLength(10)
                .HasColumnName("ca4_in3");
            entity.Property(e => e.Ca4In4)
                .HasMaxLength(10)
                .HasColumnName("ca4_in4");
            entity.Property(e => e.Ca4In5)
                .HasMaxLength(10)
                .HasColumnName("ca4_in5");
            entity.Property(e => e.Ca4In6)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("ca4_in6");
            entity.Property(e => e.Ca4In7)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("ca4_in7");
            entity.Property(e => e.Ca4In8)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("ca4_in8");
            entity.Property(e => e.Ca4In9)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("ca4_in9");
            entity.Property(e => e.Ca4Out1)
                .HasMaxLength(10)
                .HasColumnName("ca4_out1");
            entity.Property(e => e.Ca4Out2)
                .HasMaxLength(10)
                .HasColumnName("ca4_out2");
            entity.Property(e => e.Ca4Out3)
                .HasMaxLength(10)
                .HasColumnName("ca4_out3");
            entity.Property(e => e.Ca4Out4)
                .HasMaxLength(10)
                .HasColumnName("ca4_out4");
            entity.Property(e => e.Ca4Out5)
                .HasMaxLength(10)
                .HasColumnName("ca4_out5");
            entity.Property(e => e.Ca5In1)
                .HasMaxLength(10)
                .HasColumnName("ca5_in1");
            entity.Property(e => e.Ca5In10)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("ca5_in10");
            entity.Property(e => e.Ca5In2)
                .HasMaxLength(10)
                .HasColumnName("ca5_in2");
            entity.Property(e => e.Ca5In3)
                .HasMaxLength(10)
                .HasColumnName("ca5_in3");
            entity.Property(e => e.Ca5In4)
                .HasMaxLength(10)
                .HasColumnName("ca5_in4");
            entity.Property(e => e.Ca5In5)
                .HasMaxLength(10)
                .HasColumnName("ca5_in5");
            entity.Property(e => e.Ca5In6)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("ca5_in6");
            entity.Property(e => e.Ca5In7)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("ca5_in7");
            entity.Property(e => e.Ca5In8)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("ca5_in8");
            entity.Property(e => e.Ca5In9)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("ca5_in9");
            entity.Property(e => e.Ca5Out1)
                .HasMaxLength(10)
                .HasColumnName("ca5_out1");
            entity.Property(e => e.Ca5Out2)
                .HasMaxLength(10)
                .HasColumnName("ca5_out2");
            entity.Property(e => e.Ca5Out3)
                .HasMaxLength(10)
                .HasColumnName("ca5_out3");
            entity.Property(e => e.Ca5Out4)
                .HasMaxLength(10)
                .HasColumnName("ca5_out4");
            entity.Property(e => e.Ca5Out5)
                .HasMaxLength(10)
                .HasColumnName("ca5_out5");
            entity.Property(e => e.DateProcess)
                .HasColumnType("datetime")
                .HasColumnName("dateProcess");
            entity.Property(e => e.Hostname).HasMaxLength(20);
            entity.Property(e => e.ImobileLot)
                .HasMaxLength(50)
                .HasColumnName("imobileLot");
            entity.Property(e => e.ImobileSize)
                .HasMaxLength(50)
                .HasColumnName("imobileSize");
            entity.Property(e => e.ImobileType)
                .HasMaxLength(50)
                .HasColumnName("imobileType");
            entity.Property(e => e.Ipaddress)
                .HasMaxLength(20)
                .HasColumnName("IPAddress");
            entity.Property(e => e.LaserMc)
                .HasMaxLength(2)
                .HasColumnName("LaserMC");
            entity.Property(e => e.LotId)
                .ValueGeneratedOnAdd()
                .HasColumnName("lot_id");
            entity.Property(e => e.LotPo)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("lot_po");
            entity.Property(e => e.Margin)
                .HasMaxLength(10)
                .HasColumnName("margin");
            entity.Property(e => e.McPo)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("mc_po");
            entity.Property(e => e.McType)
                .HasMaxLength(10)
                .HasColumnName("mc_type");
            entity.Property(e => e.MemberId)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("member_id");
            entity.Property(e => e.NoPo)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("no_po");
            entity.Property(e => e.PoRate)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("po_rate");
            entity.Property(e => e.Process)
                .HasMaxLength(10)
                .HasColumnName("process");
            entity.Property(e => e.ProcessStep).HasColumnName("process_step");
            entity.Property(e => e.ProcessTime)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("process_time");
            entity.Property(e => e.Program).HasMaxLength(10);
            entity.Property(e => e.Remark)
                .HasMaxLength(550)
                .HasDefaultValue("-")
                .HasColumnName("remark");
            entity.Property(e => e.Result)
                .HasMaxLength(50)
                .HasColumnName("result");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("status");
            entity.Property(e => e.ThBefore)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("th_before");
            entity.Property(e => e.ThCin)
                .HasMaxLength(10)
                .HasColumnName("th_cin");
            entity.Property(e => e.ThCin2)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("th_cin2");
            entity.Property(e => e.ThCin3)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("th_cin3");
            entity.Property(e => e.ThCin4)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("th_cin4");
            entity.Property(e => e.ThCin5)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("th_cin5");
            entity.Property(e => e.ThCout1)
                .HasMaxLength(10)
                .HasColumnName("th_cout1");
            entity.Property(e => e.ThCout2)
                .HasMaxLength(10)
                .HasColumnName("th_cout2");
            entity.Property(e => e.ThCout3)
                .HasMaxLength(10)
                .HasColumnName("th_cout3");
            entity.Property(e => e.ThCout4)
                .HasMaxLength(10)
                .HasColumnName("th_cout4");
            entity.Property(e => e.ThCout5)
                .HasMaxLength(10)
                .HasColumnName("th_cout5");
            entity.Property(e => e.ThDif)
                .HasMaxLength(10)
                .HasColumnName("th_dif");
            entity.Property(e => e.TimeProcess)
                .HasColumnType("datetime")
                .HasColumnName("timeProcess");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}