// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SI24004.Models.Special;

public partial class SpecialContext : DbContext
{
    public SpecialContext(DbContextOptions<SpecialContext> options)
        : base(options)
    {
    }

    public virtual DbSet<UvirRankInvoice> UvirRankInvoices { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .UseCollation("utf8_general_ci")
            .HasCharSet("utf8");

        modelBuilder.Entity<UvirRankInvoice>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("uvir_rank_invoice");

            entity.Property(e => e.Amgt)
                .HasMaxLength(50)
                .HasColumnName("amgt");
            entity.Property(e => e.VOutput)
                .HasColumnType("int(11)")
                .HasColumnName("V_output");
            entity.Property(e => e.VPallet)
                .HasMaxLength(20)
                .HasColumnName("V_pallet");
            entity.Property(e => e.VPosite)
                .HasMaxLength(5)
                .HasColumnName("V_posite");
            entity.Property(e => e.VProduct)
                .HasMaxLength(5)
                .HasColumnName("V_product");
            entity.Property(e => e.VRank)
                .HasMaxLength(2)
                .HasColumnName("V_rank");
            entity.Property(e => e.VShipLot)
                .HasMaxLength(10)
                .HasColumnName("V_ship_lot");
            entity.Property(e => e.VSt1)
                .HasColumnType("int(11)")
                .HasColumnName("V_st1");
            entity.Property(e => e.VSt2)
                .HasColumnType("int(11)")
                .HasColumnName("V_st2");
            entity.Property(e => e.VSt3)
                .HasColumnType("int(11)")
                .HasColumnName("V_st3");
            entity.Property(e => e.VSt4)
                .HasColumnType("int(11)")
                .HasColumnName("V_st4");
            entity.Property(e => e.VSt5)
                .HasColumnType("int(11)")
                .HasColumnName("V_st5");
            entity.Property(e => e.VSt6)
                .HasColumnType("int(11)")
                .HasColumnName("V_st6");
            entity.Property(e => e.VSt7)
                .HasColumnType("int(11)")
                .HasColumnName("V_st7");
            entity.Property(e => e.VUvirLot)
                .HasMaxLength(20)
                .HasColumnName("V_uvir_lot");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}