// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SI24004.ModelsMysql;

public partial class By1Confirm
{
    public int ByItemId { get; set; }

    public string ByItemCode { get; set; }

    public string ByItemCard { get; set; }

    public string ByItemLot { get; set; }

    public string ByItemInv { get; set; }

    public string ByItemIssue { get; set; }
}