// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SI24004.ModelsMysql;

public partial class ContactInfo
{
    public int ContactId { get; set; }

    public string ContactName { get; set; }

    public string ContactDescription { get; set; }

    public string ContactAddr1 { get; set; }

    public string ContactAddr2 { get; set; }

    public string ContactCityState { get; set; }

    public string ContactCountry { get; set; }

    public string ContactPostal { get; set; }

    public string ContactPhone { get; set; }

    public string ContactFax { get; set; }

    public string ContactContact { get; set; }

    public string ContactMobile { get; set; }

    public string ContactEmail { get; set; }

    public int ContactStatus { get; set; }
}