// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SI24004.ModelsMySql;

public partial class DepartmentInfo
{
    public int DepartmentId { get; set; }

    public string DepartmentCode { get; set; }

    public string DepartmentName { get; set; }
}