// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SI24004.ModelsMysql;

public partial class From
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string LastName { get; set; }
}