// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SI24004.ModelsMySql;

public partial class IssueSlip
{
    public string IssueId { get; set; }

    public int IssuePurpose { get; set; }

    public int? CardLevel { get; set; }

    public int? IssueMember { get; set; }

    public string SlipInfo { get; set; }

    public int? SlipItem { get; set; }

    public DateTime? IssueDate { get; set; }

    public DateTime? SlipDate { get; set; }

    public int? ApproveMember { get; set; }

    public DateTime? ApproveDate { get; set; }

    public int? RejectMember { get; set; }

    public DateTime? RejectDate { get; set; }

    public int? WhReceiveMember { get; set; }

    public DateTime? WhReceiveDate { get; set; }

    public int? WhRejectMember { get; set; }

    public DateTime? WhRejectDate { get; set; }

    public int? WhApproveMember { get; set; }

    public DateTime? WhApproveDate { get; set; }

    public int? WhDiscardMember { get; set; }

    public DateTime? WhDiscardDate { get; set; }

    public int? CancelMember { get; set; }

    public DateTime? CancelDate { get; set; }

    public int IssueStatus { get; set; }
}