// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SI24004.ModelsMysql;

public partial class IssueMonth
{
    public DateOnly? PsDate { get; set; }

    public string ItemGroup { get; set; }

    public string ItemCode { get; set; }

    public string ItemName { get; set; }

    public string ItemDescription { get; set; }

    public decimal? OutQuantity { get; set; }

    public string ItemUnit { get; set; }

    public decimal? ItemPrice { get; set; }

    public string ItemCurrency { get; set; }

    public decimal? ItemAmount { get; set; }

    public string ShelfNo { get; set; }

    public string CardRemark { get; set; }

    public string SlipId { get; set; }

    public string InvNo { get; set; }

    public string IssueLotNo { get; set; }

    public string CreateSlip { get; set; }

    public string Approve { get; set; }

    public string Whissue { get; set; }
}