// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SI24004.ModelsMysql;

public partial class IssueItem
{
    public int Id { get; set; }

    public string IssueId { get; set; }

    public string ItemCode { get; set; }

    public string ItemName { get; set; }

    public string ItemType { get; set; }

    public string ItemUnit { get; set; }

    public string ItemQty { get; set; }

    public string InvLot { get; set; }

    public string LotNumber { get; set; }

    public string LotLocation { get; set; }

    public string Remark { get; set; }

    public int? RefcNo { get; set; }

    public int? ItemStatus { get; set; }
}