// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SI24004.ModelsMysql;

public partial class ItemInfo
{
    public int ItemId { get; set; }

    public int? ContactId { get; set; }

    public string ItemCode { get; set; }

    public string ItemImage { get; set; }

    public string ItemName { get; set; }

    public string ItemDescription { get; set; }

    public string ItemGroup { get; set; }

    public string ItemControl { get; set; }

    public string ItemSection { get; set; }

    public decimal? ItemQuantity { get; set; }

    public decimal? ItemHoldQuantity { get; set; }

    public decimal? ItemPrice { get; set; }

    public string ItemCurrency { get; set; }

    public string ItemUnit { get; set; }

    public int? ItemSub { get; set; }

    public string ItemSubqty { get; set; }

    public string ItemSubUnit { get; set; }

    public string ItemArea { get; set; }

    public decimal? ItemMin { get; set; }

    public decimal? ItemMax { get; set; }

    public string ItemColor { get; set; }

    public string ProductName { get; set; }

    public int? ItemChange { get; set; }

    public int? OrderStatus { get; set; }

    public int? ItemStatus { get; set; }

    public int? ItemSendFactory { get; set; }

    public int? ItemSendExpire { get; set; }

    public int? ItemIncoming { get; set; }

    public int? ItemTag { get; set; }
}