// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SI24004.ModelsMySql;

public partial class ItemBomUsageMonth
{
    public int WeekId { get; set; }

    public int? WeekBomId { get; set; }

    public string Week01 { get; set; }

    public string Week02 { get; set; }

    public string Week03 { get; set; }

    public string Week04 { get; set; }

    public string Week05 { get; set; }

    public int? WeekYear { get; set; }

    public string WeekMonth { get; set; }

    public int? WeekActive { get; set; }
}