// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SI24004.ModelsMySql;

public partial class ItemBom
{
    public int BomId { get; set; }

    public string BomType { get; set; }

    public string BomItem { get; set; }

    public string BomCustomer { get; set; }

    public string BomDepartment { get; set; }

    public double? BomYield { get; set; }

    public int BomStatus { get; set; }
}