// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SI24004.ModelsMySql;

public partial class ItemBomUsage
{
    public int PlanId { get; set; }

    public int? PlanBomId { get; set; }

    public string Plan01 { get; set; }

    public string Plan02 { get; set; }

    public string Plan03 { get; set; }

    public string Plan04 { get; set; }

    public string Plan05 { get; set; }

    public string Plan06 { get; set; }

    public string Plan07 { get; set; }

    public string Plan08 { get; set; }

    public string Plan09 { get; set; }

    public string Plan10 { get; set; }

    public string Plan11 { get; set; }

    public string Plan12 { get; set; }

    public int? PlanYear { get; set; }

    public int? PlanActive { get; set; }
}