// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SI24004.ModelsMySql;

public partial class PoFreight
{
    public int FrId { get; set; }

    public string FrDocno { get; set; }

    public DateOnly? FrDate { get; set; }

    public string FrInvoice { get; set; }

    public string FrItem { get; set; }

    public string FrAmount { get; set; }

    public string FrRate { get; set; }

    public string FrAmountThb { get; set; }

    public string FrRemark { get; set; }
}