// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SI24004.ModelsMySql;

public partial class PoReceive1
{
    public int RecNo { get; set; }

    public DateTime WhRecDate { get; set; }

    public DateTime? WhRecTime { get; set; }

    public string PsCode { get; set; }

    public string PrCode { get; set; }

    public string PrUserName { get; set; }

    public string InvoiceNo { get; set; }

    public string PoCode { get; set; }

    public string PoPdf { get; set; }

    public string PoPdf2 { get; set; }

    public string PoPdf3 { get; set; }

    public string PoPdf4 { get; set; }

    public string PoPdf5 { get; set; }

    public string PoPdf6 { get; set; }

    public string ItemCode { get; set; }

    public string ItemName { get; set; }

    public decimal ItemPrice { get; set; }

    public decimal Ordered { get; set; }

    public decimal Delivered { get; set; }

    public decimal Received { get; set; }

    public decimal Remaining { get; set; }

    public string FactoryName { get; set; }

    public int? UserId { get; set; }

    public int CardNo { get; set; }

    public int DPsitemId { get; set; }

    public string ReceiveType { get; set; }

    public string PoCurrencyUnit { get; set; }

    public decimal? PsExRate { get; set; }

    public decimal? PsUnitPrice { get; set; }

    public decimal? PsAmountThb { get; set; }

    public int? Vendor { get; set; }

    public int? IncomingId { get; set; }

    public int? IncomingResult { get; set; }
}