// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SI24004.ModelsMySql;

public partial class RemainShelf
{
    public int ItemId { get; set; }

    public string ItemCode { get; set; }

    public string ItemName { get; set; }

    public string ItemDescription { get; set; }

    public string InvNo { get; set; }

    public string ReceiveLotNo { get; set; }

    public decimal? InQuantity { get; set; }

    public string ContactName { get; set; }

    public string Description { get; set; }

    public string RecordDate { get; set; }

    public string ItemUnit { get; set; }

    public string InvDate { get; set; }

    public string ExDate { get; set; }

    public int? Diff { get; set; }

    public string ItemSection { get; set; }

    public string ShelfNo { get; set; }

    public string ShelfQty { get; set; }
}