// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SI24004.ModelsMysql;

public partial class ShelfInfo
{
    public int SefIId { get; set; }

    public int? SefIArea { get; set; }

    public string SefIName { get; set; }

    public string SefISize { get; set; }

    public string SefIStatus { get; set; }
}