// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SI24004.ModelsMySql;

public partial class SqlConnect : DbContext
{
    public SqlConnect(DbContextOptions<SqlConnect> options)
        : base(options)
    {
    }

    public virtual DbSet<By1Confirm> By1Confirms { get; set; }

    public virtual DbSet<ContactInfo> ContactInfos { get; set; }

    public virtual DbSet<CurrencyRate> CurrencyRates { get; set; }

    public virtual DbSet<DepartmentInfo> DepartmentInfos { get; set; }

    public virtual DbSet<From> Froms { get; set; }

    public virtual DbSet<IssueConfirm> IssueConfirms { get; set; }

    public virtual DbSet<IssueItem> IssueItems { get; set; }

    public virtual DbSet<IssueMonth> IssueMonths { get; set; }

    public virtual DbSet<IssueSlip> IssueSlips { get; set; }

    public virtual DbSet<ItemBalance> ItemBalances { get; set; }

    public virtual DbSet<ItemBom> ItemBoms { get; set; }

    public virtual DbSet<ItemBomList> ItemBomLists { get; set; }

    public virtual DbSet<ItemBomOut> ItemBomOuts { get; set; }

    public virtual DbSet<ItemBomStock> ItemBomStocks { get; set; }

    public virtual DbSet<ItemBomUsage> ItemBomUsages { get; set; }

    public virtual DbSet<ItemBomUsageMonth> ItemBomUsageMonths { get; set; }

    public virtual DbSet<ItemInfo> ItemInfos { get; set; }

    public virtual DbSet<ItemLife> ItemLives { get; set; }

    public virtual DbSet<PoFreight> PoFreights { get; set; }

    public virtual DbSet<PoReceive> PoReceives { get; set; }

    public virtual DbSet<PoReceive1> PoReceive1s { get; set; }

    public virtual DbSet<ReceiveMonth> ReceiveMonths { get; set; }

    public virtual DbSet<RemainShelf> RemainShelves { get; set; }

    public virtual DbSet<SectionInfo> SectionInfos { get; set; }

    public virtual DbSet<ShelfInfo> ShelfInfos { get; set; }

    public virtual DbSet<ShelfLife> ShelfLives { get; set; }

    public virtual DbSet<StockCard> StockCards { get; set; }

    public virtual DbSet<StockShelf> StockShelves { get; set; }

    public virtual DbSet<UpdateOut> UpdateOuts { get; set; }

    public virtual DbSet<UserGroup> UserGroups { get; set; }

    public virtual DbSet<UserGroup1> UserGroups1 { get; set; }

    public virtual DbSet<UserInfo> UserInfos { get; set; }

    public virtual DbSet<WhArea> WhAreas { get; set; }

    public virtual DbSet<WhPath> WhPaths { get; set; }

    public virtual DbSet<WhProduct> WhProducts { get; set; }

    public virtual DbSet<WhPurpose> WhPurposes { get; set; }

    public virtual DbSet<WhStatus> WhStatuses { get; set; }

    public virtual DbSet<WhType> WhTypes { get; set; }

    public virtual DbSet<WhUpdate> WhUpdates { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .UseCollation("utf8_general_ci")
            .HasCharSet("utf8");

        modelBuilder.Entity<By1Confirm>(entity =>
        {
            entity.HasKey(e => e.ByItemId).HasName("PRIMARY");

            entity.ToTable("by1_confirm");

            entity.Property(e => e.ByItemId)
                .HasColumnType("int(11)")
                .HasColumnName("by_item_id");
            entity.Property(e => e.ByItemCard)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("by_item_card");
            entity.Property(e => e.ByItemCode)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("by_item_code");
            entity.Property(e => e.ByItemInv)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("by_item_inv");
            entity.Property(e => e.ByItemIssue)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("by_item_issue");
            entity.Property(e => e.ByItemLot)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("by_item_lot");
        });

        modelBuilder.Entity<ContactInfo>(entity =>
        {
            entity.HasKey(e => e.ContactId).HasName("PRIMARY");

            entity.ToTable("contact_info");

            entity.Property(e => e.ContactId)
                .ValueGeneratedNever()
                .HasColumnType("int(11)")
                .HasColumnName("Contact_ID");
            entity.Property(e => e.ContactAddr1)
                .HasMaxLength(80)
                .HasColumnName("Contact_Addr1");
            entity.Property(e => e.ContactAddr2)
                .HasMaxLength(80)
                .HasColumnName("Contact_Addr2");
            entity.Property(e => e.ContactCityState)
                .HasMaxLength(60)
                .HasColumnName("Contact_CityState");
            entity.Property(e => e.ContactContact)
                .HasMaxLength(80)
                .HasColumnName("Contact_Contact");
            entity.Property(e => e.ContactCountry)
                .HasMaxLength(30)
                .HasColumnName("Contact_Country");
            entity.Property(e => e.ContactDescription)
                .HasMaxLength(100)
                .HasColumnName("Contact_Description");
            entity.Property(e => e.ContactEmail)
                .HasMaxLength(50)
                .HasColumnName("Contact_Email");
            entity.Property(e => e.ContactFax)
                .HasMaxLength(30)
                .HasColumnName("Contact_FAX");
            entity.Property(e => e.ContactMobile)
                .HasMaxLength(30)
                .HasColumnName("Contact_Mobile");
            entity.Property(e => e.ContactName)
                .IsRequired()
                .HasMaxLength(60)
                .HasDefaultValueSql("''")
                .HasColumnName("Contact_Name");
            entity.Property(e => e.ContactPhone)
                .HasMaxLength(30)
                .HasColumnName("Contact_Phone");
            entity.Property(e => e.ContactPostal)
                .HasMaxLength(20)
                .HasColumnName("Contact_Postal");
            entity.Property(e => e.ContactStatus)
                .HasDefaultValueSql("'1'")
                .HasColumnType("int(11)")
                .HasColumnName("Contact_Status");
        });

        modelBuilder.Entity<CurrencyRate>(entity =>
        {
            entity.HasKey(e => e.CurId).HasName("PRIMARY");

            entity.ToTable("currency_rate");

            entity.HasIndex(e => new { e.CurDate, e.CurCode }, "cur_date");

            entity.Property(e => e.CurId)
                .HasColumnType("bigint(20)")
                .HasColumnName("cur_id");
            entity.Property(e => e.CurCode)
                .HasMaxLength(4)
                .IsFixedLength()
                .HasColumnName("cur_code");
            entity.Property(e => e.CurDate)
                .HasColumnType("datetime")
                .HasColumnName("cur_date");
            entity.Property(e => e.CurDescription)
                .HasMaxLength(60)
                .HasColumnName("cur_description");
            entity.Property(e => e.CurSource)
                .HasMaxLength(60)
                .HasColumnName("cur_source");
            entity.Property(e => e.CurTtb)
                .HasPrecision(10, 6)
                .HasColumnName("cur_ttb");
            entity.Property(e => e.CurTts)
                .HasPrecision(10, 6)
                .HasColumnName("cur_tts");
            entity.Property(e => e.CurUpdate)
                .HasColumnType("datetime")
                .HasColumnName("cur_update");
            entity.Property(e => e.UserId)
                .HasColumnType("int(11)")
                .HasColumnName("user_id");
            entity.Property(e => e.UserName)
                .HasMaxLength(60)
                .HasColumnName("user_name");
        });

        modelBuilder.Entity<DepartmentInfo>(entity =>
        {
            entity.HasKey(e => e.DepartmentId).HasName("PRIMARY");

            entity.ToTable("department_info");

            entity.Property(e => e.DepartmentId)
                .ValueGeneratedNever()
                .HasColumnType("int(11)")
                .HasColumnName("department_id");
            entity.Property(e => e.DepartmentCode)
                .HasMaxLength(55)
                .HasColumnName("department_code");
            entity.Property(e => e.DepartmentName)
                .HasMaxLength(255)
                .HasColumnName("department_name");
        });

        modelBuilder.Entity<From>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("froms");

            entity.Property(e => e.Id)
                .HasColumnType("int(11)")
                .HasColumnName("id");
            entity.Property(e => e.LastName)
                .HasMaxLength(255)
                .HasColumnName("last_name");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("name");
        });

        modelBuilder.Entity<IssueConfirm>(entity =>
        {
            entity.HasKey(e => e.SqId).HasName("PRIMARY");

            entity.ToTable("issue_confirm");

            entity.Property(e => e.SqId)
                .HasColumnType("int(11)")
                .HasColumnName("Sq_ID");
            entity.Property(e => e.CardNo)
                .HasColumnType("int(11)")
                .HasColumnName("Card_No");
            entity.Property(e => e.ExpireDate).HasColumnName("Expire_Date");
            entity.Property(e => e.InvNo)
                .HasMaxLength(255)
                .HasColumnName("Inv_No");
            entity.Property(e => e.ItemCode)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Item_Code");
            entity.Property(e => e.LotNo)
                .HasMaxLength(255)
                .HasColumnName("Lot_No");
            entity.Property(e => e.QrInput)
                .HasColumnType("int(11)")
                .HasColumnName("QR_Input");
            entity.Property(e => e.QrOutput)
                .HasColumnType("int(11)")
                .HasColumnName("QR_Output");
            entity.Property(e => e.SlipId)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("Slip_ID");
            entity.Property(e => e.SlipStatus)
                .HasColumnType("int(11)")
                .HasColumnName("Slip_Status");
        });

        modelBuilder.Entity<IssueItem>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("issue_item");

            entity.Property(e => e.Id)
                .HasColumnType("int(11)")
                .HasColumnName("id");
            entity.Property(e => e.InvLot)
                .HasMaxLength(50)
                .HasColumnName("inv_lot");
            entity.Property(e => e.IssueId)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("issue_id");
            entity.Property(e => e.ItemCode)
                .HasMaxLength(20)
                .HasColumnName("item_code");
            entity.Property(e => e.ItemName)
                .HasColumnType("text")
                .HasColumnName("item_name");
            entity.Property(e => e.ItemQty)
                .HasMaxLength(15)
                .HasColumnName("item_qty");
            entity.Property(e => e.ItemStatus)
                .HasDefaultValueSql("'1'")
                .HasColumnType("int(11)")
                .HasColumnName("item_status");
            entity.Property(e => e.ItemType)
                .HasMaxLength(255)
                .HasColumnName("item_type");
            entity.Property(e => e.ItemUnit)
                .HasMaxLength(15)
                .HasColumnName("item_unit");
            entity.Property(e => e.LotLocation)
                .HasMaxLength(20)
                .HasColumnName("lot_location");
            entity.Property(e => e.LotNumber)
                .HasMaxLength(20)
                .HasColumnName("lot_number");
            entity.Property(e => e.RefcNo)
                .HasColumnType("int(11)")
                .HasColumnName("refc_no");
            entity.Property(e => e.Remark)
                .HasColumnType("text")
                .HasColumnName("remark");
        });

        modelBuilder.Entity<IssueMonth>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("issue_month");

            entity.Property(e => e.Approve).HasColumnType("text");
            entity.Property(e => e.CardRemark)
                .HasMaxLength(255)
                .HasColumnName("Card_Remark");
            entity.Property(e => e.CreateSlip).HasColumnType("text");
            entity.Property(e => e.InvNo)
                .HasMaxLength(50)
                .HasColumnName("Inv_No");
            entity.Property(e => e.IssueLotNo)
                .HasMaxLength(500)
                .HasColumnName("Issue_Lot_No");
            entity.Property(e => e.ItemAmount)
                .HasPrecision(30, 4)
                .HasColumnName("Item_Amount");
            entity.Property(e => e.ItemCode)
                .HasMaxLength(50)
                .IsFixedLength()
                .HasColumnName("item_code");
            entity.Property(e => e.ItemCurrency)
                .HasMaxLength(10)
                .HasDefaultValueSql("'bath'")
                .IsFixedLength()
                .HasColumnName("Item_Currency");
            entity.Property(e => e.ItemDescription)
                .HasMaxLength(250)
                .HasColumnName("Item_Description");
            entity.Property(e => e.ItemGroup)
                .HasMaxLength(80)
                .HasColumnName("Item_Group");
            entity.Property(e => e.ItemName)
                .HasMaxLength(80)
                .HasColumnName("Item_Name");
            entity.Property(e => e.ItemPrice)
                .HasPrecision(15, 2)
                .HasDefaultValueSql("'0.00'")
                .HasColumnName("Item_Price");
            entity.Property(e => e.ItemUnit)
                .HasMaxLength(10)
                .HasColumnName("item_unit");
            entity.Property(e => e.OutQuantity)
                .HasPrecision(15, 2)
                .HasDefaultValueSql("'0.00'")
                .HasColumnName("Out_Quantity");
            entity.Property(e => e.PsDate).HasColumnName("PS_Date");
            entity.Property(e => e.ShelfNo)
                .HasMaxLength(10)
                .HasColumnName("shelf_no");
            entity.Property(e => e.SlipId)
                .HasMaxLength(20)
                .HasColumnName("Slip_ID");
            entity.Property(e => e.Whissue)
                .HasColumnType("text")
                .HasColumnName("WHIssue");
        });

        modelBuilder.Entity<IssueSlip>(entity =>
        {
            entity.HasKey(e => e.IssueId).HasName("PRIMARY");

            entity.ToTable("issue_slip");

            entity.Property(e => e.IssueId)
                .HasMaxLength(20)
                .HasColumnName("issue_id");
            entity.Property(e => e.ApproveDate)
                .HasColumnType("datetime")
                .HasColumnName("approve_date");
            entity.Property(e => e.ApproveMember)
                .HasColumnType("int(11)")
                .HasColumnName("approve_member");
            entity.Property(e => e.CancelDate)
                .HasColumnType("datetime")
                .HasColumnName("cancel_date");
            entity.Property(e => e.CancelMember)
                .HasColumnType("int(11)")
                .HasColumnName("cancel_member");
            entity.Property(e => e.CardLevel)
                .HasDefaultValueSql("'1'")
                .HasColumnType("int(11)")
                .HasColumnName("card_level");
            entity.Property(e => e.IssueDate)
                .HasColumnType("datetime")
                .HasColumnName("issue_date");
            entity.Property(e => e.IssueMember)
                .HasColumnType("int(11)")
                .HasColumnName("issue_member");
            entity.Property(e => e.IssuePurpose)
                .HasColumnType("int(11)")
                .HasColumnName("issue_purpose");
            entity.Property(e => e.IssueStatus)
                .HasDefaultValueSql("'1'")
                .HasColumnType("int(11)")
                .HasColumnName("issue_status");
            entity.Property(e => e.RejectDate)
                .HasColumnType("datetime")
                .HasColumnName("reject_date");
            entity.Property(e => e.RejectMember)
                .HasColumnType("int(11)")
                .HasColumnName("reject_member");
            entity.Property(e => e.SlipDate)
                .HasColumnType("datetime")
                .HasColumnName("slip_date");
            entity.Property(e => e.SlipInfo)
                .HasMaxLength(250)
                .HasColumnName("slip_info");
            entity.Property(e => e.SlipItem)
                .HasColumnType("int(11)")
                .HasColumnName("slip_item");
            entity.Property(e => e.WhApproveDate)
                .HasColumnType("datetime")
                .HasColumnName("wh_approve_date");
            entity.Property(e => e.WhApproveMember)
                .HasColumnType("int(11)")
                .HasColumnName("wh_approve_member");
            entity.Property(e => e.WhDiscardDate)
                .HasColumnType("datetime")
                .HasColumnName("wh_discard_date");
            entity.Property(e => e.WhDiscardMember)
                .HasColumnType("int(11)")
                .HasColumnName("wh_discard_member");
            entity.Property(e => e.WhReceiveDate)
                .HasColumnType("datetime")
                .HasColumnName("wh_receive_date");
            entity.Property(e => e.WhReceiveMember)
                .HasColumnType("int(11)")
                .HasColumnName("wh_receive_member");
            entity.Property(e => e.WhRejectDate)
                .HasColumnType("datetime")
                .HasColumnName("wh_reject_date");
            entity.Property(e => e.WhRejectMember)
                .HasColumnType("int(11)")
                .HasColumnName("wh_reject_member");
        });

        modelBuilder.Entity<ItemBalance>(entity =>
        {
            entity.HasKey(e => e.BlId).HasName("PRIMARY");

            entity.ToTable("item_balance");

            entity.Property(e => e.BlId)
                .HasColumnType("int(11)")
                .HasColumnName("bl_id");
            entity.Property(e => e.BlAmount)
                .HasPrecision(20, 2)
                .HasColumnName("bl_amount");
            entity.Property(e => e.BlItemCode)
                .HasMaxLength(20)
                .HasColumnName("bl_item_code");
            entity.Property(e => e.BlItemId)
                .HasColumnType("int(11)")
                .HasColumnName("bl_item_id");
            entity.Property(e => e.BlMonth)
                .HasMaxLength(10)
                .HasColumnName("bl_month");
            entity.Property(e => e.BlPrice)
                .HasPrecision(20, 2)
                .HasColumnName("bl_price");
            entity.Property(e => e.BlQty)
                .HasPrecision(20, 2)
                .HasColumnName("bl_qty");
        });

        modelBuilder.Entity<ItemBom>(entity =>
        {
            entity.HasKey(e => e.BomId).HasName("PRIMARY");

            entity.ToTable("item_bom");

            entity.Property(e => e.BomId)
                .HasColumnType("int(11)")
                .HasColumnName("BOM_ID");
            entity.Property(e => e.BomCustomer)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("BOM_Customer");
            entity.Property(e => e.BomDepartment)
                .HasMaxLength(50)
                .HasColumnName("BOM_Department");
            entity.Property(e => e.BomItem)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("BOM_Item");
            entity.Property(e => e.BomStatus)
                .HasColumnType("int(11)")
                .HasColumnName("BOM_Status");
            entity.Property(e => e.BomType)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("BOM_Type");
            entity.Property(e => e.BomYield)
                .HasColumnType("double(5,2)")
                .HasColumnName("BOM_Yield");
        });

        modelBuilder.Entity<ItemBomList>(entity =>
        {
            entity.HasKey(e => e.BomId).HasName("PRIMARY");

            entity.ToTable("item_bom_list");

            entity.Property(e => e.BomId)
                .HasColumnType("int(11)")
                .HasColumnName("bom_id");
            entity.Property(e => e.BomActive)
                .HasColumnType("int(11)")
                .HasColumnName("bom_active");
            entity.Property(e => e.BomItemId)
                .HasColumnType("int(11)")
                .HasColumnName("bom_item_id");
            entity.Property(e => e.BomList)
                .HasColumnType("int(11)")
                .HasColumnName("bom_list");
            entity.Property(e => e.BomMainUsage)
                .HasMaxLength(10)
                .HasColumnName("bom_main_usage");
            entity.Property(e => e.BomRemain)
                .HasMaxLength(10)
                .HasColumnName("bom_remain");
            entity.Property(e => e.BomSection)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("bom_section");
            entity.Property(e => e.BomUsage)
                .HasMaxLength(10)
                .HasColumnName("bom_usage");
            entity.Property(e => e.BomYield)
                .HasMaxLength(5)
                .HasColumnName("bom_yield");
        });

        modelBuilder.Entity<ItemBomOut>(entity =>
        {
            entity.HasKey(e => e.OutId).HasName("PRIMARY");

            entity.ToTable("item_bom_out");

            entity.Property(e => e.OutId)
                .HasColumnType("int(11)")
                .HasColumnName("out_id");
            entity.Property(e => e.OutDate).HasColumnName("out_date");
            entity.Property(e => e.OutItem)
                .HasMaxLength(20)
                .HasColumnName("out_item");
            entity.Property(e => e.OutQty)
                .HasMaxLength(11)
                .HasColumnName("out_qty");
        });

        modelBuilder.Entity<ItemBomStock>(entity =>
        {
            entity.HasKey(e => e.StockId).HasName("PRIMARY");

            entity.ToTable("item_bom_stock");

            entity.Property(e => e.StockId)
                .HasColumnType("int(11)")
                .HasColumnName("stock_id");
            entity.Property(e => e.Stock01)
                .HasMaxLength(11)
                .HasColumnName("stock_01");
            entity.Property(e => e.Stock02)
                .HasMaxLength(11)
                .HasColumnName("stock_02");
            entity.Property(e => e.Stock03)
                .HasMaxLength(11)
                .HasColumnName("stock_03");
            entity.Property(e => e.Stock04)
                .HasMaxLength(11)
                .HasColumnName("stock_04");
            entity.Property(e => e.Stock05)
                .HasMaxLength(11)
                .HasColumnName("stock_05");
            entity.Property(e => e.Stock06)
                .HasMaxLength(11)
                .HasColumnName("stock_06");
            entity.Property(e => e.Stock07)
                .HasMaxLength(11)
                .HasColumnName("stock_07");
            entity.Property(e => e.Stock08)
                .HasMaxLength(11)
                .HasColumnName("stock_08");
            entity.Property(e => e.Stock09)
                .HasMaxLength(11)
                .HasColumnName("stock_09");
            entity.Property(e => e.Stock10)
                .HasMaxLength(11)
                .HasColumnName("stock_10");
            entity.Property(e => e.Stock11)
                .HasMaxLength(11)
                .HasColumnName("stock_11");
            entity.Property(e => e.Stock12)
                .HasMaxLength(11)
                .HasColumnName("stock_12");
            entity.Property(e => e.StockBomId)
                .HasColumnType("int(11)")
                .HasColumnName("stock_bom_id");
            entity.Property(e => e.StockItemId)
                .HasColumnType("int(11)")
                .HasColumnName("stock_item_id");
            entity.Property(e => e.StockYear)
                .HasMaxLength(10)
                .HasColumnName("stock_year");
        });

        modelBuilder.Entity<ItemBomUsage>(entity =>
        {
            entity.HasKey(e => e.PlanId).HasName("PRIMARY");

            entity.ToTable("item_bom_usage");

            entity.Property(e => e.PlanId)
                .HasColumnType("int(11)")
                .HasColumnName("plan_id");
            entity.Property(e => e.Plan01)
                .HasMaxLength(20)
                .HasColumnName("plan_01");
            entity.Property(e => e.Plan02)
                .HasMaxLength(20)
                .HasColumnName("plan_02");
            entity.Property(e => e.Plan03)
                .HasMaxLength(20)
                .HasColumnName("plan_03");
            entity.Property(e => e.Plan04)
                .HasMaxLength(20)
                .HasColumnName("plan_04");
            entity.Property(e => e.Plan05)
                .HasMaxLength(20)
                .HasColumnName("plan_05");
            entity.Property(e => e.Plan06)
                .HasMaxLength(20)
                .HasColumnName("plan_06");
            entity.Property(e => e.Plan07)
                .HasMaxLength(20)
                .HasColumnName("plan_07");
            entity.Property(e => e.Plan08)
                .HasMaxLength(20)
                .HasColumnName("plan_08");
            entity.Property(e => e.Plan09)
                .HasMaxLength(20)
                .HasColumnName("plan_09");
            entity.Property(e => e.Plan10)
                .HasMaxLength(20)
                .HasColumnName("plan_10");
            entity.Property(e => e.Plan11)
                .HasMaxLength(20)
                .HasColumnName("plan_11");
            entity.Property(e => e.Plan12)
                .HasMaxLength(20)
                .HasColumnName("plan_12");
            entity.Property(e => e.PlanActive)
                .HasDefaultValueSql("'0'")
                .HasColumnType("int(11)")
                .HasColumnName("plan_active");
            entity.Property(e => e.PlanBomId)
                .HasColumnType("int(11)")
                .HasColumnName("plan_bom_id");
            entity.Property(e => e.PlanYear)
                .HasColumnType("int(11)")
                .HasColumnName("plan_year");
        });

        modelBuilder.Entity<ItemBomUsageMonth>(entity =>
        {
            entity.HasKey(e => e.WeekId).HasName("PRIMARY");

            entity.ToTable("item_bom_usage_month");

            entity.Property(e => e.WeekId)
                .HasColumnType("int(11)")
                .HasColumnName("week_id");
            entity.Property(e => e.Week01)
                .HasMaxLength(20)
                .HasColumnName("week_01");
            entity.Property(e => e.Week02)
                .HasMaxLength(20)
                .HasColumnName("week_02");
            entity.Property(e => e.Week03)
                .HasMaxLength(20)
                .HasColumnName("week_03");
            entity.Property(e => e.Week04)
                .HasMaxLength(20)
                .HasColumnName("week_04");
            entity.Property(e => e.Week05)
                .HasMaxLength(20)
                .HasColumnName("week_05");
            entity.Property(e => e.WeekActive)
                .HasDefaultValueSql("'0'")
                .HasColumnType("int(11)")
                .HasColumnName("week_active");
            entity.Property(e => e.WeekBomId)
                .HasColumnType("int(11)")
                .HasColumnName("week_bom_id");
            entity.Property(e => e.WeekMonth)
                .HasMaxLength(2)
                .HasColumnName("week_month");
            entity.Property(e => e.WeekYear)
                .HasColumnType("int(11)")
                .HasColumnName("week_year");
        });

        modelBuilder.Entity<ItemInfo>(entity =>
        {
            entity.HasKey(e => e.ItemId).HasName("PRIMARY");

            entity.ToTable("item_info");

            entity.HasIndex(e => e.ItemCode, "iCode").IsUnique();

            entity.HasIndex(e => e.ItemName, "iName").HasAnnotation("MySql:FullTextIndex", true);

            entity.Property(e => e.ItemId)
                .HasColumnType("int(11)")
                .HasColumnName("Item_ID");
            entity.Property(e => e.ContactId)
                .HasColumnType("int(11)")
                .HasColumnName("Contact_ID");
            entity.Property(e => e.ItemArea)
                .HasMaxLength(10)
                .HasColumnName("Item_Area");
            entity.Property(e => e.ItemChange)
                .HasColumnType("int(11)")
                .HasColumnName("Item_Change");
            entity.Property(e => e.ItemCode)
                .HasMaxLength(50)
                .IsFixedLength()
                .HasColumnName("Item_Code");
            entity.Property(e => e.ItemColor)
                .HasMaxLength(50)
                .HasColumnName("Item_Color");
            entity.Property(e => e.ItemControl)
                .HasMaxLength(10)
                .HasColumnName("Item_Control");
            entity.Property(e => e.ItemCurrency)
                .HasMaxLength(10)
                .HasDefaultValueSql("'bath'")
                .IsFixedLength()
                .HasColumnName("Item_Currency");
            entity.Property(e => e.ItemDescription)
                .HasMaxLength(250)
                .HasColumnName("Item_Description");
            entity.Property(e => e.ItemGroup)
                .HasMaxLength(80)
                .HasColumnName("Item_Group");
            entity.Property(e => e.ItemHoldQuantity)
                .HasPrecision(15, 2)
                .HasColumnName("Item_Hold_Quantity");
            entity.Property(e => e.ItemImage)
                .HasColumnType("text")
                .HasColumnName("Item_Image");
            entity.Property(e => e.ItemIncoming)
                .HasColumnType("int(11)")
                .HasColumnName("Item_Incoming");
            entity.Property(e => e.ItemMax)
                .HasPrecision(11, 2)
                .HasDefaultValueSql("'0.00'")
                .HasColumnName("Item_Max");
            entity.Property(e => e.ItemMin)
                .HasPrecision(11, 2)
                .HasDefaultValueSql("'0.00'")
                .HasColumnName("Item_Min");
            entity.Property(e => e.ItemName)
                .HasMaxLength(80)
                .HasColumnName("Item_Name");
            entity.Property(e => e.ItemPrice)
                .HasPrecision(15, 2)
                .HasDefaultValueSql("'0.00'")
                .HasColumnName("Item_Price");
            entity.Property(e => e.ItemQuantity)
                .HasPrecision(15, 2)
                .HasDefaultValueSql("'0.00'")
                .HasColumnName("Item_Quantity");
            entity.Property(e => e.ItemSection)
                .HasMaxLength(50)
                .HasColumnName("Item_Section");
            entity.Property(e => e.ItemSendExpire)
                .HasDefaultValueSql("'0'")
                .HasColumnType("int(11)")
                .HasColumnName("Item_sendExpire");
            entity.Property(e => e.ItemSendFactory)
                .HasColumnType("int(11)")
                .HasColumnName("Item_sendFactory");
            entity.Property(e => e.ItemStatus)
                .HasDefaultValueSql("'1'")
                .HasColumnType("int(11)")
                .HasColumnName("Item_Status");
            entity.Property(e => e.ItemSub)
                .HasColumnType("int(11)")
                .HasColumnName("Item_Sub");
            entity.Property(e => e.ItemSubUnit)
                .HasMaxLength(255)
                .HasColumnName("Item_SubUnit");
            entity.Property(e => e.ItemSubqty)
                .HasMaxLength(10)
                .HasColumnName("Item_Subqty");
            entity.Property(e => e.ItemTag)
                .HasColumnType("int(11)")
                .HasColumnName("Item_Tag");
            entity.Property(e => e.ItemUnit)
                .HasMaxLength(10)
                .HasColumnName("Item_Unit");
            entity.Property(e => e.OrderStatus)
                .HasDefaultValueSql("'0'")
                .HasColumnType("int(11)")
                .HasColumnName("Order_Status");
            entity.Property(e => e.ProductName)
                .HasMaxLength(50)
                .HasColumnName("Product_Name");
        });

        modelBuilder.Entity<ItemLife>(entity =>
        {
            entity.HasKey(e => e.ItemId).HasName("PRIMARY");

            entity.ToTable("item_life");

            entity.Property(e => e.ItemId)
                .ValueGeneratedNever()
                .HasColumnType("int(11)")
                .HasColumnName("item_id");
            entity.Property(e => e.Description)
                .HasColumnType("text")
                .HasColumnName("description");
            entity.Property(e => e.Expire)
                .HasMaxLength(10)
                .HasColumnName("expire");
            entity.Property(e => e.ItemCode)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("item_code");
            entity.Property(e => e.RefControl)
                .HasColumnType("text")
                .HasColumnName("ref_control");
            entity.Property(e => e.RefDescription)
                .HasMaxLength(200)
                .HasColumnName("ref_description");
            entity.Property(e => e.RefFormat)
                .HasMaxLength(20)
                .HasColumnName("ref_format");
            entity.Property(e => e.RefKeep)
                .HasColumnType("text")
                .HasColumnName("ref_keep");
            entity.Property(e => e.RefProtect)
                .HasColumnType("text")
                .HasColumnName("ref_protect");
            entity.Property(e => e.RefSignal)
                .HasMaxLength(255)
                .HasColumnName("ref_signal");
            entity.Property(e => e.RefWarning)
                .HasMaxLength(255)
                .HasColumnName("ref_warning");
        });

        modelBuilder.Entity<PoFreight>(entity =>
        {
            entity.HasKey(e => e.FrId).HasName("PRIMARY");

            entity.ToTable("po_freight");

            entity.Property(e => e.FrId)
                .HasColumnType("int(11)")
                .HasColumnName("fr_id");
            entity.Property(e => e.FrAmount)
                .HasMaxLength(100)
                .HasColumnName("fr_amount");
            entity.Property(e => e.FrAmountThb)
                .HasMaxLength(100)
                .HasColumnName("fr_amountTHB");
            entity.Property(e => e.FrDate).HasColumnName("fr_date");
            entity.Property(e => e.FrDocno)
                .HasMaxLength(50)
                .HasColumnName("fr_docno");
            entity.Property(e => e.FrInvoice)
                .HasMaxLength(255)
                .HasColumnName("fr_invoice");
            entity.Property(e => e.FrItem)
                .HasMaxLength(50)
                .HasColumnName("fr_item");
            entity.Property(e => e.FrRate)
                .HasMaxLength(20)
                .HasColumnName("fr_rate");
            entity.Property(e => e.FrRemark)
                .HasMaxLength(255)
                .HasColumnName("fr_remark");
        });

        modelBuilder.Entity<PoReceive>(entity =>
        {
            entity.HasKey(e => e.RecNo).HasName("PRIMARY");

            entity.ToTable("po_receive");

            entity.HasIndex(e => e.ItemName, "Item_Name");

            entity.HasIndex(e => e.ItemCode, "iCode_Receive");

            entity.Property(e => e.RecNo)
                .HasColumnType("int(11)")
                .HasColumnName("Rec_No");
            entity.Property(e => e.CardNo)
                .HasColumnType("int(11)")
                .HasColumnName("Card_No");
            entity.Property(e => e.DPsitemId)
                .HasColumnType("int(11)")
                .HasColumnName("dPSItem_ID");
            entity.Property(e => e.Delivered).HasPrecision(15, 2);
            entity.Property(e => e.FactoryName)
                .HasMaxLength(5)
                .HasDefaultValueSql("'OE'")
                .HasColumnName("Factory_Name");
            entity.Property(e => e.IncomingId)
                .HasColumnType("int(11)")
                .HasColumnName("incoming_id");
            entity.Property(e => e.IncomingResult)
                .HasColumnType("int(11)")
                .HasColumnName("incoming_result");
            entity.Property(e => e.InvoiceNo)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("Invoice_No");
            entity.Property(e => e.ItemCode)
                .IsRequired()
                .HasMaxLength(15)
                .IsFixedLength()
                .HasColumnName("Item_Code");
            entity.Property(e => e.ItemName)
                .IsRequired()
                .HasMaxLength(80)
                .HasColumnName("Item_Name");
            entity.Property(e => e.ItemPrice)
                .HasPrecision(15, 2)
                .HasColumnName("Item_Price");
            entity.Property(e => e.Ordered).HasPrecision(15, 2);
            entity.Property(e => e.PoCode)
                .IsRequired()
                .HasMaxLength(50)
                .IsFixedLength()
                .HasColumnName("PO_Code");
            entity.Property(e => e.PoCurrencyUnit)
                .HasMaxLength(10)
                .IsFixedLength()
                .HasColumnName("PO_Currency_Unit");
            entity.Property(e => e.PoPdf)
                .HasMaxLength(255)
                .HasColumnName("PO_PDF");
            entity.Property(e => e.PoPdf2)
                .HasMaxLength(255)
                .HasColumnName("PO_PDF2");
            entity.Property(e => e.PoPdf3)
                .HasMaxLength(255)
                .HasColumnName("PO_PDF3");
            entity.Property(e => e.PoPdf4)
                .HasMaxLength(255)
                .HasColumnName("PO_PDF4");
            entity.Property(e => e.PoPdf5)
                .HasMaxLength(255)
                .HasColumnName("PO_PDF5");
            entity.Property(e => e.PoPdf6)
                .HasMaxLength(255)
                .HasColumnName("PO_PDF6");
            entity.Property(e => e.PrCode)
                .IsRequired()
                .HasMaxLength(50)
                .IsFixedLength()
                .HasColumnName("PR_Code");
            entity.Property(e => e.PrUserName)
                .IsRequired()
                .HasMaxLength(60)
                .HasColumnName("PR_User_Name");
            entity.Property(e => e.PsAmountThb)
                .HasPrecision(15, 2)
                .HasColumnName("PS_Amount_THB");
            entity.Property(e => e.PsCode)
                .HasMaxLength(50)
                .HasColumnName("PS_Code");
            entity.Property(e => e.PsExRate)
                .HasPrecision(15, 5)
                .HasColumnName("PS_ExRate");
            entity.Property(e => e.PsUnitPrice)
                .HasPrecision(15, 2)
                .HasColumnName("PS_Unit_Price");
            entity.Property(e => e.ReceiveType)
                .IsRequired()
                .HasMaxLength(10)
                .HasDefaultValueSql("'Nomal'")
                .IsFixedLength()
                .HasColumnName("Receive_Type");
            entity.Property(e => e.Received).HasPrecision(15, 2);
            entity.Property(e => e.Remaining).HasPrecision(15, 2);
            entity.Property(e => e.UserId)
                .HasColumnType("int(11)")
                .HasColumnName("User_ID");
            entity.Property(e => e.Vendor).HasColumnType("int(11)");
            entity.Property(e => e.WhRecDate)
                .HasColumnType("datetime")
                .HasColumnName("WH_Rec_Date");
            entity.Property(e => e.WhRecTime)
                .HasColumnType("datetime")
                .HasColumnName("WH_Rec_Time");
        });

        modelBuilder.Entity<PoReceive1>(entity =>
        {
            entity.HasKey(e => e.RecNo).HasName("PRIMARY");

            entity.ToTable("po_receive1");

            entity.HasIndex(e => e.ItemName, "Item_Name");

            entity.HasIndex(e => e.ItemCode, "iCode_Receive");

            entity.Property(e => e.RecNo)
                .HasColumnType("int(11)")
                .HasColumnName("Rec_No");
            entity.Property(e => e.CardNo)
                .HasColumnType("int(11)")
                .HasColumnName("Card_No");
            entity.Property(e => e.DPsitemId)
                .HasColumnType("int(11)")
                .HasColumnName("dPSItem_ID");
            entity.Property(e => e.Delivered).HasPrecision(15, 2);
            entity.Property(e => e.FactoryName)
                .HasMaxLength(5)
                .HasDefaultValueSql("'OE'")
                .HasColumnName("Factory_Name");
            entity.Property(e => e.IncomingId)
                .HasColumnType("int(11)")
                .HasColumnName("incoming_id");
            entity.Property(e => e.IncomingResult)
                .HasColumnType("int(11)")
                .HasColumnName("incoming_result");
            entity.Property(e => e.InvoiceNo)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("Invoice_No");
            entity.Property(e => e.ItemCode)
                .IsRequired()
                .HasMaxLength(15)
                .IsFixedLength()
                .HasColumnName("Item_Code");
            entity.Property(e => e.ItemName)
                .IsRequired()
                .HasMaxLength(80)
                .HasColumnName("Item_Name");
            entity.Property(e => e.ItemPrice)
                .HasPrecision(15, 2)
                .HasColumnName("Item_Price");
            entity.Property(e => e.Ordered).HasPrecision(15, 2);
            entity.Property(e => e.PoCode)
                .IsRequired()
                .HasMaxLength(50)
                .IsFixedLength()
                .HasColumnName("PO_Code");
            entity.Property(e => e.PoCurrencyUnit)
                .HasMaxLength(10)
                .IsFixedLength()
                .HasColumnName("PO_Currency_Unit");
            entity.Property(e => e.PoPdf)
                .HasMaxLength(255)
                .HasColumnName("PO_PDF");
            entity.Property(e => e.PoPdf2)
                .HasMaxLength(255)
                .HasColumnName("PO_PDF2");
            entity.Property(e => e.PoPdf3)
                .HasMaxLength(255)
                .HasColumnName("PO_PDF3");
            entity.Property(e => e.PoPdf4)
                .HasMaxLength(255)
                .HasColumnName("PO_PDF4");
            entity.Property(e => e.PoPdf5)
                .HasMaxLength(255)
                .HasColumnName("PO_PDF5");
            entity.Property(e => e.PoPdf6)
                .HasMaxLength(255)
                .HasColumnName("PO_PDF6");
            entity.Property(e => e.PrCode)
                .IsRequired()
                .HasMaxLength(50)
                .IsFixedLength()
                .HasColumnName("PR_Code");
            entity.Property(e => e.PrUserName)
                .IsRequired()
                .HasMaxLength(60)
                .HasColumnName("PR_User_Name");
            entity.Property(e => e.PsAmountThb)
                .HasPrecision(15, 2)
                .HasColumnName("PS_Amount_THB");
            entity.Property(e => e.PsCode)
                .HasMaxLength(50)
                .HasColumnName("PS_Code");
            entity.Property(e => e.PsExRate)
                .HasPrecision(15, 5)
                .HasColumnName("PS_ExRate");
            entity.Property(e => e.PsUnitPrice)
                .HasPrecision(15, 2)
                .HasColumnName("PS_Unit_Price");
            entity.Property(e => e.ReceiveType)
                .IsRequired()
                .HasMaxLength(10)
                .HasDefaultValueSql("'Nomal'")
                .IsFixedLength()
                .HasColumnName("Receive_Type");
            entity.Property(e => e.Received).HasPrecision(15, 2);
            entity.Property(e => e.Remaining).HasPrecision(15, 2);
            entity.Property(e => e.UserId)
                .HasColumnType("int(11)")
                .HasColumnName("User_ID");
            entity.Property(e => e.Vendor).HasColumnType("int(11)");
            entity.Property(e => e.WhRecDate)
                .HasColumnType("datetime")
                .HasColumnName("WH_Rec_Date");
            entity.Property(e => e.WhRecTime)
                .HasColumnType("datetime")
                .HasColumnName("WH_Rec_Time");
        });

        modelBuilder.Entity<ReceiveMonth>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("receive_month");

            entity.Property(e => e.CardDate).HasColumnName("Card_Date");
            entity.Property(e => e.ContactName)
                .HasMaxLength(60)
                .HasDefaultValueSql("''")
                .HasColumnName("Contact_Name");
            entity.Property(e => e.ExpireDate)
                .HasDefaultValueSql("'0000-00-00'")
                .HasColumnName("Expire_Date");
            entity.Property(e => e.InQuantity)
                .HasPrecision(15, 2)
                .HasDefaultValueSql("'0.00'")
                .HasColumnName("In_Quantity");
            entity.Property(e => e.InvNo)
                .HasMaxLength(50)
                .HasColumnName("Inv_No");
            entity.Property(e => e.ItemAmount)
                .HasPrecision(15, 2)
                .HasDefaultValueSql("'0.00'")
                .HasColumnName("Item_Amount");
            entity.Property(e => e.ItemCardNo)
                .HasDefaultValueSql("'0'")
                .HasColumnType("int(11)")
                .HasColumnName("Item_Card_No");
            entity.Property(e => e.ItemCode)
                .HasMaxLength(50)
                .IsFixedLength()
                .HasColumnName("Item_Code");
            entity.Property(e => e.ItemCurrency)
                .HasMaxLength(10)
                .HasDefaultValueSql("'bath'")
                .IsFixedLength()
                .HasColumnName("Item_Currency");
            entity.Property(e => e.ItemDescription)
                .HasMaxLength(250)
                .HasColumnName("Item_Description");
            entity.Property(e => e.ItemName)
                .HasMaxLength(80)
                .HasColumnName("Item_Name");
            entity.Property(e => e.ItemPrice)
                .HasPrecision(15, 2)
                .HasDefaultValueSql("'0.00'")
                .HasColumnName("Item_Price");
            entity.Property(e => e.PoNo)
                .HasMaxLength(50)
                .HasColumnName("PO_No");
            entity.Property(e => e.ReceiveLotNo)
                .HasMaxLength(500)
                .HasColumnName("Receive_Lot_No");
        });

        modelBuilder.Entity<RemainShelf>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("remain_shelf");

            entity.Property(e => e.ContactName)
                .IsRequired()
                .HasMaxLength(60)
                .HasDefaultValueSql("''")
                .HasColumnName("Contact_Name");
            entity.Property(e => e.Description)
                .HasColumnType("text")
                .HasColumnName("description");
            entity.Property(e => e.Diff)
                .HasColumnType("int(7)")
                .HasColumnName("diff");
            entity.Property(e => e.ExDate)
                .HasMaxLength(40)
                .HasColumnName("Ex_Date")
                .UseCollation("utf8mb4_general_ci")
                .HasCharSet("utf8mb4");
            entity.Property(e => e.InQuantity)
                .HasPrecision(15, 2)
                .HasDefaultValueSql("'0.00'")
                .HasColumnName("In_Quantity");
            entity.Property(e => e.InvDate)
                .HasMaxLength(40)
                .HasColumnName("Inv_Date")
                .UseCollation("utf8mb4_general_ci")
                .HasCharSet("utf8mb4");
            entity.Property(e => e.InvNo)
                .HasMaxLength(50)
                .HasColumnName("Inv_No");
            entity.Property(e => e.ItemCode)
                .HasMaxLength(50)
                .IsFixedLength()
                .HasColumnName("Item_Code");
            entity.Property(e => e.ItemDescription)
                .HasMaxLength(250)
                .HasColumnName("Item_Description");
            entity.Property(e => e.ItemId)
                .HasColumnType("int(11)")
                .HasColumnName("Item_ID");
            entity.Property(e => e.ItemName)
                .HasMaxLength(80)
                .HasColumnName("Item_Name");
            entity.Property(e => e.ItemSection)
                .HasMaxLength(50)
                .HasColumnName("Item_Section");
            entity.Property(e => e.ItemUnit)
                .HasMaxLength(10)
                .HasColumnName("Item_Unit");
            entity.Property(e => e.ReceiveLotNo)
                .HasMaxLength(500)
                .HasColumnName("Receive_Lot_No");
            entity.Property(e => e.RecordDate)
                .HasMaxLength(40)
                .HasColumnName("Record_Date")
                .UseCollation("utf8mb4_general_ci")
                .HasCharSet("utf8mb4");
            entity.Property(e => e.ShelfNo)
                .HasMaxLength(10)
                .HasColumnName("Shelf_No");
            entity.Property(e => e.ShelfQty)
                .HasMaxLength(10)
                .HasColumnName("Shelf_Qty");
        });

        modelBuilder.Entity<SectionInfo>(entity =>
        {
            entity.HasKey(e => e.SectionId).HasName("PRIMARY");

            entity.ToTable("section_info");

            entity.Property(e => e.SectionId)
                .HasColumnType("int(11)")
                .HasColumnName("Section_ID");
            entity.Property(e => e.BudgetCode)
                .HasMaxLength(10)
                .IsFixedLength()
                .HasColumnName("Budget_Code");
            entity.Property(e => e.DepartmentId)
                .HasColumnType("int(11)")
                .HasColumnName("Department_ID");
            entity.Property(e => e.FactoryName)
                .IsRequired()
                .HasMaxLength(5)
                .IsFixedLength()
                .HasColumnName("Factory_Name");
            entity.Property(e => e.SectionCode)
                .IsRequired()
                .HasMaxLength(10)
                .IsFixedLength()
                .HasColumnName("Section_Code");
            entity.Property(e => e.SectionDescription)
                .HasMaxLength(255)
                .HasColumnName("Section_Description");
            entity.Property(e => e.SectionName)
                .IsRequired()
                .HasMaxLength(60)
                .HasColumnName("Section_Name");
            entity.Property(e => e.SectionStatus)
                .HasColumnType("int(11)")
                .HasColumnName("Section_Status");
        });

        modelBuilder.Entity<ShelfInfo>(entity =>
        {
            entity.HasKey(e => e.SefIId).HasName("PRIMARY");

            entity.ToTable("shelf_info");

            entity.Property(e => e.SefIId)
                .HasColumnType("int(11)")
                .HasColumnName("SefI_ID");
            entity.Property(e => e.SefIArea)
                .HasColumnType("int(11)")
                .HasColumnName("SefI_Area");
            entity.Property(e => e.SefIName)
                .HasMaxLength(100)
                .HasColumnName("SefI_Name");
            entity.Property(e => e.SefISize)
                .HasMaxLength(10)
                .HasColumnName("SefI_Size");
            entity.Property(e => e.SefIStatus)
                .HasMaxLength(2)
                .HasColumnName("SefI_Status");
        });

        modelBuilder.Entity<ShelfLife>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("shelf_life");

            entity.Property(e => e.ContactName)
                .IsRequired()
                .HasMaxLength(60)
                .HasDefaultValueSql("''")
                .HasColumnName("Contact_Name");
            entity.Property(e => e.Description)
                .HasColumnType("text")
                .HasColumnName("description");
            entity.Property(e => e.Diff)
                .HasColumnType("int(7)")
                .HasColumnName("diff");
            entity.Property(e => e.ExDate)
                .HasMaxLength(40)
                .HasColumnName("Ex_Date")
                .UseCollation("utf8mb4_general_ci")
                .HasCharSet("utf8mb4");
            entity.Property(e => e.InQuantity)
                .HasPrecision(15, 2)
                .HasDefaultValueSql("'0.00'")
                .HasColumnName("In_Quantity");
            entity.Property(e => e.InvDate)
                .HasMaxLength(40)
                .HasColumnName("Inv_Date")
                .UseCollation("utf8mb4_general_ci")
                .HasCharSet("utf8mb4");
            entity.Property(e => e.InvNo)
                .HasMaxLength(50)
                .HasColumnName("Inv_No");
            entity.Property(e => e.ItemCode)
                .HasMaxLength(50)
                .IsFixedLength()
                .HasColumnName("Item_Code");
            entity.Property(e => e.ItemDescription)
                .HasMaxLength(250)
                .HasColumnName("Item_Description");
            entity.Property(e => e.ItemId)
                .HasColumnType("int(11)")
                .HasColumnName("Item_ID");
            entity.Property(e => e.ItemName)
                .HasMaxLength(80)
                .HasColumnName("Item_Name");
            entity.Property(e => e.ItemSection)
                .HasMaxLength(50)
                .HasColumnName("Item_Section");
            entity.Property(e => e.ItemUnit)
                .HasMaxLength(10)
                .HasColumnName("Item_Unit");
            entity.Property(e => e.ReceiveLotNo)
                .HasMaxLength(500)
                .HasColumnName("Receive_Lot_No");
            entity.Property(e => e.RecordDate)
                .HasMaxLength(40)
                .HasColumnName("Record_Date")
                .UseCollation("utf8mb4_general_ci")
                .HasCharSet("utf8mb4");
            entity.Property(e => e.ShelfNo)
                .HasMaxLength(10)
                .HasColumnName("Shelf_No");
            entity.Property(e => e.ShelfQty)
                .HasMaxLength(10)
                .HasColumnName("Shelf_Qty");
        });

        modelBuilder.Entity<StockCard>(entity =>
        {
            entity.HasKey(e => e.CardNo).HasName("PRIMARY");

            entity.ToTable("stock_card");

            entity.HasIndex(e => new { e.ItemId, e.ItemCode }, "IDX_iCode");

            entity.Property(e => e.CardNo)
                .HasColumnType("int(11)")
                .HasColumnName("Card_No");
            entity.Property(e => e.BeforeQuantity)
                .HasPrecision(15, 2)
                .HasColumnName("Before_Quantity");
            entity.Property(e => e.CardDate).HasColumnName("Card_Date");
            entity.Property(e => e.CardHoldRemark)
                .HasMaxLength(255)
                .HasColumnName("Card_Hold_Remark");
            entity.Property(e => e.CardLv)
                .HasDefaultValueSql("'1'")
                .HasColumnType("int(11)")
                .HasColumnName("Card_Lv");
            entity.Property(e => e.CardRemark)
                .HasMaxLength(255)
                .HasColumnName("Card_Remark");
            entity.Property(e => e.CardType)
                .HasMaxLength(2)
                .HasDefaultValueSql("''")
                .IsFixedLength()
                .HasColumnName("Card_Type");
            entity.Property(e => e.ExpireDate)
                .HasDefaultValueSql("'0000-00-00'")
                .HasColumnName("Expire_Date");
            entity.Property(e => e.HoldQuantity)
                .HasPrecision(15, 2)
                .HasDefaultValueSql("'0.00'")
                .HasColumnName("Hold_Quantity");
            entity.Property(e => e.InQuantity)
                .HasPrecision(15, 2)
                .HasDefaultValueSql("'0.00'")
                .HasColumnName("In_Quantity");
            entity.Property(e => e.InvNo)
                .HasMaxLength(50)
                .HasColumnName("Inv_No");
            entity.Property(e => e.InvoiceDate)
                .HasDefaultValueSql("'0000-00-00'")
                .HasColumnName("Invoice_Date");
            entity.Property(e => e.IssueLotNo)
                .HasMaxLength(500)
                .HasColumnName("Issue_Lot_No");
            entity.Property(e => e.ItemAmount)
                .HasPrecision(15, 2)
                .HasDefaultValueSql("'0.00'")
                .HasColumnName("Item_Amount");
            entity.Property(e => e.ItemAmountThb)
                .HasPrecision(15, 2)
                .HasColumnName("Item_Amount_THB");
            entity.Property(e => e.ItemCardNo)
                .HasDefaultValueSql("'0'")
                .HasColumnType("int(11)")
                .HasColumnName("Item_Card_No");
            entity.Property(e => e.ItemCode)
                .HasMaxLength(50)
                .HasColumnName("Item_Code");
            entity.Property(e => e.ItemId)
                .HasColumnType("int(11)")
                .HasColumnName("Item_ID");
            entity.Property(e => e.ItemName)
                .HasMaxLength(80)
                .HasColumnName("Item_Name");
            entity.Property(e => e.ItemPrice)
                .HasPrecision(15, 2)
                .HasDefaultValueSql("'0.00'")
                .HasColumnName("Item_Price");
            entity.Property(e => e.ItemPriceThb)
                .HasPrecision(15, 2)
                .HasColumnName("Item_Price_THB");
            entity.Property(e => e.LastUpdate)
                .HasMaxLength(1)
                .HasDefaultValueSql("'T'")
                .HasColumnName("Last_Update");
            entity.Property(e => e.OutQuantity)
                .HasPrecision(15, 2)
                .HasDefaultValueSql("'0.00'")
                .HasColumnName("Out_Quantity");
            entity.Property(e => e.PoCurrencyUnit)
                .HasMaxLength(10)
                .IsFixedLength()
                .HasColumnName("PO_Currency_Unit");
            entity.Property(e => e.PoNo)
                .HasMaxLength(50)
                .HasColumnName("PO_No");
            entity.Property(e => e.PsCode)
                .HasMaxLength(50)
                .HasColumnName("PS_Code");
            entity.Property(e => e.ReceiveLotNo)
                .HasMaxLength(500)
                .HasColumnName("Receive_Lot_No");
            entity.Property(e => e.RecordDate).HasColumnName("Record_Date");
            entity.Property(e => e.RecordTime)
                .HasMaxLength(20)
                .IsFixedLength()
                .HasColumnName("Record_Time");
            entity.Property(e => e.RefCardNo)
                .HasDefaultValueSql("'0'")
                .HasColumnType("int(11)")
                .HasColumnName("Ref_Card_No");
            entity.Property(e => e.RemainStock)
                .HasPrecision(15, 2)
                .HasColumnName("Remain_Stock");
            entity.Property(e => e.ReturnQuantity)
                .HasPrecision(15, 2)
                .HasDefaultValueSql("'0.00'")
                .HasColumnName("Return_Quantity");
            entity.Property(e => e.ShelfId)
                .HasColumnType("int(11)")
                .HasColumnName("Shelf_ID");
            entity.Property(e => e.SlipId)
                .HasMaxLength(20)
                .HasColumnName("Slip_ID");
            entity.Property(e => e.TagConfirm)
                .HasMaxLength(20)
                .HasColumnName("Tag_Confirm");
            entity.Property(e => e.TagPrint)
                .HasColumnType("int(11)")
                .HasColumnName("Tag_Print");
            entity.Property(e => e.TagQa)
                .HasColumnType("int(11)")
                .HasColumnName("Tag_QA");
            entity.Property(e => e.UpdateQuantity)
                .HasPrecision(15, 2)
                .HasDefaultValueSql("'0.00'")
                .HasColumnName("Update_Quantity");
            entity.Property(e => e.UserId)
                .HasColumnType("int(11)")
                .HasColumnName("User_ID");
            entity.Property(e => e.WhcItemFactory)
                .HasMaxLength(10)
                .HasDefaultValueSql("'OE'")
                .IsFixedLength()
                .HasColumnName("WHC_Item_Factory");
            entity.Property(e => e.WorkerName)
                .HasMaxLength(255)
                .HasColumnName("Worker_Name");
        });

        modelBuilder.Entity<StockShelf>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("stock_shelf");

            entity.Property(e => e.Id)
                .HasColumnType("int(11)")
                .HasColumnName("id");
            entity.Property(e => e.CardId)
                .HasColumnType("int(11)")
                .HasColumnName("card_id");
            entity.Property(e => e.Fact)
                .HasMaxLength(1)
                .HasColumnName("fact");
            entity.Property(e => e.ItemId)
                .HasColumnType("int(11)")
                .HasColumnName("item_id");
            entity.Property(e => e.ShelfHold)
                .HasMaxLength(255)
                .HasColumnName("shelf_hold");
            entity.Property(e => e.ShelfNo)
                .HasMaxLength(10)
                .HasColumnName("shelf_no");
            entity.Property(e => e.ShelfQty)
                .HasMaxLength(10)
                .HasColumnName("shelf_qty");
            entity.Property(e => e.SlipId)
                .HasColumnType("int(11)")
                .HasColumnName("slip_id");
            entity.Property(e => e.WhId)
                .HasColumnType("int(11)")
                .HasColumnName("wh_id");
        });

        modelBuilder.Entity<UpdateOut>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("update_out");

            entity.Property(e => e.CardDate).HasColumnName("card_date");
            entity.Property(e => e.ItemCode)
                .HasMaxLength(50)
                .HasColumnName("Item_Code");
            entity.Property(e => e.ItemId)
                .HasColumnType("int(11)")
                .HasColumnName("Item_ID");
            entity.Property(e => e.Qty)
                .HasPrecision(37, 2)
                .HasColumnName("qty");
        });

        modelBuilder.Entity<UserGroup>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("user_groups")
                .HasCharSet("latin1")
                .UseCollation("latin1_swedish_ci");

            entity.HasIndex(e => e.GroupLevel, "group_level").IsUnique();

            entity.Property(e => e.Id)
                .HasColumnType("int(11)")
                .HasColumnName("id");
            entity.Property(e => e.GroupLevel)
                .HasColumnType("int(11)")
                .HasColumnName("group_level");
            entity.Property(e => e.GroupName)
                .IsRequired()
                .HasMaxLength(150)
                .HasColumnName("group_name");
            entity.Property(e => e.GroupStatus)
                .HasColumnType("int(11)")
                .HasColumnName("group_status");
        });

        modelBuilder.Entity<UserGroup1>(entity =>
        {
            entity.HasKey(e => e.UserGroupId).HasName("PRIMARY");

            entity.ToTable("user_group");

            entity.Property(e => e.UserGroupId)
                .HasColumnType("int(11)")
                .HasColumnName("User_Group_ID");
            entity.Property(e => e.UserGroupDescription)
                .HasMaxLength(255)
                .HasColumnName("User_Group_Description");
            entity.Property(e => e.UserGroupLevel)
                .HasColumnType("int(11)")
                .HasColumnName("User_Group_Level");
            entity.Property(e => e.UserGroupName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("User_Group_Name");
            entity.Property(e => e.UserGroupStatus)
                .HasDefaultValueSql("'1'")
                .HasColumnType("int(11)")
                .HasColumnName("User_Group_Status");
        });

        modelBuilder.Entity<UserInfo>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PRIMARY");

            entity.ToTable("user_info");

            entity.Property(e => e.UserId)
                .HasColumnType("int(11)")
                .HasColumnName("User_ID");
            entity.Property(e => e.LastLogin)
                .HasColumnType("datetime")
                .HasColumnName("Last_Login");
            entity.Property(e => e.SectionId)
                .HasColumnType("int(11)")
                .HasColumnName("Section_ID");
            entity.Property(e => e.UserCode)
                .HasColumnType("int(11)")
                .HasColumnName("User_Code");
            entity.Property(e => e.UserEmail)
                .HasMaxLength(250)
                .HasColumnName("User_Email");
            entity.Property(e => e.UserFullname)
                .HasMaxLength(550)
                .HasColumnName("User_Fullname");
            entity.Property(e => e.UserGroupId)
                .HasColumnType("int(11)")
                .HasColumnName("User_Group_ID");
            entity.Property(e => e.UserImage)
                .HasMaxLength(255)
                .HasColumnName("User_Image");
            entity.Property(e => e.UserLevel)
                .HasDefaultValueSql("'3'")
                .HasColumnType("int(11)")
                .HasColumnName("User_Level");
            entity.Property(e => e.UserLoginName)
                .HasMaxLength(30)
                .HasColumnName("User_LoginName");
            entity.Property(e => e.UserPassword)
                .HasMaxLength(30)
                .IsFixedLength()
                .HasColumnName("User_Password");
            entity.Property(e => e.UserStatus)
                .HasColumnType("int(11)")
                .HasColumnName("User_Status");
        });

        modelBuilder.Entity<WhArea>(entity =>
        {
            entity.HasKey(e => e.ShelfId).HasName("PRIMARY");

            entity.ToTable("wh_area");

            entity.HasIndex(e => e.ShelfName, "name").IsUnique();

            entity.Property(e => e.ShelfId)
                .HasColumnType("int(11)")
                .HasColumnName("shelf_id");
            entity.Property(e => e.ShelfColumn)
                .HasColumnType("int(11)")
                .HasColumnName("shelf_column");
            entity.Property(e => e.ShelfDescription)
                .HasMaxLength(500)
                .HasColumnName("shelf_description");
            entity.Property(e => e.ShelfName)
                .HasMaxLength(50)
                .HasColumnName("shelf_name");
            entity.Property(e => e.ShelfRow)
                .HasColumnType("int(11)")
                .HasColumnName("shelf_row");
            entity.Property(e => e.ShelfStatus)
                .HasColumnType("int(11)")
                .HasColumnName("shelf_status");
        });

        modelBuilder.Entity<WhPath>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("wh_path");

            entity.Property(e => e.Active)
                .HasColumnType("int(11)")
                .HasColumnName("active");
            entity.Property(e => e.PathName)
                .HasColumnType("text")
                .HasColumnName("path_name");
        });

        modelBuilder.Entity<WhProduct>(entity =>
        {
            entity.HasKey(e => e.TypeId).HasName("PRIMARY");

            entity.ToTable("wh_product");

            entity.Property(e => e.TypeId)
                .ValueGeneratedNever()
                .HasColumnType("int(11)")
                .HasColumnName("type_id");
            entity.Property(e => e.TypeName)
                .HasMaxLength(50)
                .HasColumnName("type_name");
        });

        modelBuilder.Entity<WhPurpose>(entity =>
        {
            entity.HasKey(e => e.PurposeId).HasName("PRIMARY");

            entity.ToTable("wh_purpose");

            entity.Property(e => e.PurposeId)
                .HasColumnType("int(11)")
                .HasColumnName("purpose_id");
            entity.Property(e => e.PurposeNameEn)
                .HasMaxLength(255)
                .HasColumnName("purpose_name_en");
            entity.Property(e => e.PurposeNameTh)
                .HasMaxLength(255)
                .HasColumnName("purpose_name_th");
            entity.Property(e => e.PurposeStatus)
                .HasColumnType("int(11)")
                .HasColumnName("purpose_status");
        });

        modelBuilder.Entity<WhStatus>(entity =>
        {
            entity.HasKey(e => e.SId).HasName("PRIMARY");

            entity.ToTable("wh_status");

            entity.Property(e => e.SId)
                .HasColumnType("int(11)")
                .HasColumnName("s_id");
            entity.Property(e => e.SName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("s_name");
        });

        modelBuilder.Entity<WhType>(entity =>
        {
            entity.HasKey(e => e.TypeId).HasName("PRIMARY");

            entity.ToTable("wh_type");

            entity.Property(e => e.TypeId)
                .HasColumnType("int(11)")
                .HasColumnName("type_id");
            entity.Property(e => e.TypeNameEn)
                .HasMaxLength(250)
                .HasColumnName("type_name_en");
            entity.Property(e => e.TypeNameTh)
                .HasMaxLength(250)
                .HasColumnName("type_name_th");
            entity.Property(e => e.TypeStatus)
                .HasDefaultValueSql("'1'")
                .HasColumnType("int(11)")
                .HasColumnName("type_status");
        });

        modelBuilder.Entity<WhUpdate>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("wh_update");

            entity.Property(e => e.ProDate)
                .HasColumnType("datetime")
                .HasColumnName("pro_date");
            entity.Property(e => e.ProStatus)
                .HasColumnType("int(11)")
                .HasColumnName("pro_status");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}