// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SI24004.ModelsMysql;

public partial class StockCard
{
    public int CardNo { get; set; }

    public DateOnly? CardDate { get; set; }

    public string CardType { get; set; }

    public int? UserId { get; set; }

    public int? ItemId { get; set; }

    public string ItemCode { get; set; }

    public string ItemName { get; set; }

    public string PsCode { get; set; }

    public string PoNo { get; set; }

    public string InvNo { get; set; }

    public string ReceiveLotNo { get; set; }

    public string IssueLotNo { get; set; }

    public decimal? ItemPrice { get; set; }

    public decimal? ItemAmount { get; set; }

    public decimal? ItemPriceThb { get; set; }

    public decimal? ItemAmountThb { get; set; }

    public decimal? BeforeQuantity { get; set; }

    public decimal? UpdateQuantity { get; set; }

    public decimal? InQuantity { get; set; }

    public decimal? OutQuantity { get; set; }

    public decimal? HoldQuantity { get; set; }

    public decimal? ReturnQuantity { get; set; }

    public string CardRemark { get; set; }

    public int? TagQa { get; set; }

    public int? TagPrint { get; set; }

    public string WorkerName { get; set; }

    public int? RefCardNo { get; set; }

    public string LastUpdate { get; set; }

    public string WhcItemFactory { get; set; }

    public DateOnly? RecordDate { get; set; }

    public string RecordTime { get; set; }

    public int? CardLv { get; set; }

    public string CardHoldRemark { get; set; }

    public int? ItemCardNo { get; set; }

    public string PoCurrencyUnit { get; set; }

    public string SlipId { get; set; }

    public DateOnly? ExpireDate { get; set; }

    public DateOnly? InvoiceDate { get; set; }

    public decimal? RemainStock { get; set; }

    public int? ShelfId { get; set; }

    public string TagConfirm { get; set; }
}