// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SI24004.ModelsMysql;

public partial class UserGroup1
{
    public int UserGroupId { get; set; }

    public string UserGroupName { get; set; }

    public string UserGroupDescription { get; set; }

    public int? UserGroupLevel { get; set; }

    public int UserGroupStatus { get; set; }
}