// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SI24004.ModelsMySql;

public partial class UserInfo
{
    public int UserId { get; set; }

    public int UserGroupId { get; set; }

    public int SectionId { get; set; }

    public int? UserCode { get; set; }

    public string UserLoginName { get; set; }

    public string UserPassword { get; set; }

    public string UserFullname { get; set; }

    public string UserEmail { get; set; }

    public string UserImage { get; set; }

    public int UserStatus { get; set; }

    public int? UserLevel { get; set; }

    public DateTime? LastLogin { get; set; }
}