// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SI24004.ModelsMySql;

public partial class WhArea
{
    public int ShelfId { get; set; }

    public string ShelfName { get; set; }

    public int? ShelfRow { get; set; }

    public int? ShelfColumn { get; set; }

    public string ShelfDescription { get; set; }

    public int? ShelfStatus { get; set; }
}