// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SI24004.ModelsMysql;

public partial class WhStatus
{
    public int SId { get; set; }

    public string SName { get; set; }
}