// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SI24004.ModelsMysql;

public partial class ItemBalance1
{
    public int BlId { get; set; }

    public int? BlItemId { get; set; }

    public string BlItemCode { get; set; }

    public decimal? BlPrice { get; set; }

    public decimal? BlQty { get; set; }

    public decimal? BlAmount { get; set; }

    public string BlMonth { get; set; }
}