// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SI24004.ModelsMysql;

public partial class SectionInfo
{
    public int SectionId { get; set; }

    public string FactoryName { get; set; }

    public int? DepartmentId { get; set; }

    public string BudgetCode { get; set; }

    public string SectionCode { get; set; }

    public string SectionName { get; set; }

    public string SectionDescription { get; set; }

    public int? SectionStatus { get; set; }
}