// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SI24004.ModelsMysql;

public partial class WhUpdate
{
    public int? ProStatus { get; set; }

    public DateTime? ProDate { get; set; }
}