// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SI24004.Models.SqlServer1;

public partial class OutputDefectA0400
{
    public long? Mfmasrl { get; set; }

    public string Ltlotno { get; set; }

    public long? Mfpidrev { get; set; }

    public string Mfprcid { get; set; }

    public long? Mfinpqn { get; set; }

    public long? Mfoutqn { get; set; }

    public long? Mfoutav { get; set; }

    public long? Mfoutho { get; set; }

    public long? Mfrjqan { get; set; }

    public string Mfrjdes { get; set; }

    public string Yield { get; set; }

    public DateTime? Mfmandt { get; set; }

    public DateTime? Mfmanpd { get; set; }

    public string Glasstype { get; set; }

    public string Mfpidcus { get; set; }

    public string Mfpidgl { get; set; }

    public string Ltinvst { get; set; }

    public string Mfeqpid { get; set; }

    public string McTime { get; set; }

    public string Mfpadse { get; set; }

    public string Mfshelf { get; set; }

    public string Mfinspe { get; set; }

    public string Ltfmelt { get; set; }

    public long? Mfmanty { get; set; }

    public long? Ltoprid { get; set; }

    public string Mfchpad { get; set; }

    public string Mflappad { get; set; }

    public string Mfplpad { get; set; }

    public string Mfcoatseq { get; set; }

    public string Lttyhis { get; set; }

    public string Mfstcod { get; set; }

    public string Mfstdet { get; set; }

    public long? Mfmaotb { get; set; }

    public long? Lttmid1 { get; set; }

    public string Flpflnm { get; set; }

    public long? Mfoumid { get; set; }

    public long? Good { get; set; }

    public long? ThicknessOver { get; set; }

    public long? NrOver { get; set; }

    public long? Broken { get; set; }

    public long? Other { get; set; }

    public long? Scratch { get; set; }

    public long? Chip { get; set; }

    public long? Sample { get; set; }

    public long? Handling { get; set; }

    public long? Crack { get; set; }

    public long? Lost { get; set; }

    public long? FringeOverScrapped { get; set; }

    public long? CrackBeforeLoad { get; set; }

    public long? ChipBeforeLoad { get; set; }

    public long? ScratchBeforeLoad { get; set; }

    public long? HandlingBeforeLoad { get; set; }

    public long? BrokenBeforeLoad { get; set; }

    public long? OrangePeelH { get; set; }

    public long? PolishZujiR { get; set; }

    public long? BrokenH { get; set; }

    public long? OtherH { get; set; }

    public long? DataH { get; set; }

    public long? TNLow { get; set; }

    public long? HdMc { get; set; }

    public long? HdAg { get; set; }

    public long? HdTn { get; set; }

    public long? HdNr { get; set; }

    public long? HdHw { get; set; }

    public long? HdTf { get; set; }

    public long? HdPost { get; set; }

    public long? DullScratchR { get; set; }

    public long? ThkDiffH { get; set; }

    public string ParameterGa { get; set; }

    public string ParameterGb { get; set; }

    public string ParameterGc { get; set; }

    public string ParameterThk { get; set; }

    public string Thickness1 { get; set; }

    public string Thickness2 { get; set; }

    public string Thickness3 { get; set; }

    public string Thickness4 { get; set; }

    public string Thickness5 { get; set; }

    public string Dimension1 { get; set; }

    public string Dimension2 { get; set; }

    public string Dimension3 { get; set; }

    public string Dimension4 { get; set; }

    public string Dimension5 { get; set; }

    public string Corner1 { get; set; }

    public string Corner2 { get; set; }

    public string Corner3 { get; set; }

    public string Corner4 { get; set; }

    public string Corner5 { get; set; }

    public string Series1 { get; set; }

    public string Series2 { get; set; }

    public string Series3 { get; set; }

    public string Series4 { get; set; }

    public string Series5 { get; set; }

    public string WidthLenghtA1 { get; set; }

    public string WidthLenghtA2 { get; set; }

    public string WidthLenghtB1 { get; set; }

    public string WidthLenghtB2 { get; set; }

    public string CornerA1 { get; set; }

    public string CornerA2 { get; set; }

    public string CornerB1 { get; set; }

    public string CornerB2 { get; set; }

    public string EdgeA1 { get; set; }

    public string EdgeA2 { get; set; }

    public string EdgeB1 { get; set; }

    public string EdgeB2 { get; set; }

    public string ThkBefore { get; set; }

    public string ThkAfter { get; set; }

    public string PadLot { get; set; }

    public string PadTime { get; set; }

    public string SlurryTot { get; set; }

    public string SlurryTime { get; set; }

    public string PolishingTime { get; set; }

    public string Stair1 { get; set; }

    public string Stair2 { get; set; }

    public string Stair3 { get; set; }

    public string Stair4 { get; set; }

    public string Stair5 { get; set; }

    public string Stair6 { get; set; }

    public string Stair7 { get; set; }
}