// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SI24004.Models.SqlServer1;

public partial class OutputContext : DbContext
{
    public OutputContext(DbContextOptions<OutputContext> options)
        : base(options)
    {
    }

    public virtual DbSet<OutputDefectA0400> OutputDefectA0400s { get; set; }

    public virtual DbSet<OutputDefectA0400Realtime> OutputDefectA0400Realtimes { get; set; }

    public virtual DbSet<OutputDefectA0600> OutputDefectA0600s { get; set; }

    public virtual DbSet<OutputDefectA0600Realtime> OutputDefectA0600Realtimes { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<OutputDefectA0400>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("Output_Defect_A0400");

            entity.Property(e => e.Broken).HasColumnName("broken");
            entity.Property(e => e.BrokenBeforeLoad).HasColumnName("broken before load");
            entity.Property(e => e.BrokenH).HasColumnName("broken(h)");
            entity.Property(e => e.Chip).HasColumnName("chip");
            entity.Property(e => e.ChipBeforeLoad).HasColumnName("chip before load");
            entity.Property(e => e.Corner1)
                .IsUnicode(false)
                .HasColumnName("corner-1");
            entity.Property(e => e.Corner2)
                .IsUnicode(false)
                .HasColumnName("corner-2");
            entity.Property(e => e.Corner3)
                .IsUnicode(false)
                .HasColumnName("corner-3");
            entity.Property(e => e.Corner4)
                .IsUnicode(false)
                .HasColumnName("corner-4");
            entity.Property(e => e.Corner5)
                .IsUnicode(false)
                .HasColumnName("corner-5");
            entity.Property(e => e.CornerA1)
                .IsUnicode(false)
                .HasColumnName("corner-a1");
            entity.Property(e => e.CornerA2)
                .IsUnicode(false)
                .HasColumnName("corner-a2");
            entity.Property(e => e.CornerB1)
                .IsUnicode(false)
                .HasColumnName("corner-b1");
            entity.Property(e => e.CornerB2)
                .IsUnicode(false)
                .HasColumnName("corner-b2");
            entity.Property(e => e.Crack).HasColumnName("crack");
            entity.Property(e => e.CrackBeforeLoad).HasColumnName("crack before load");
            entity.Property(e => e.DataH).HasColumnName("data(h)");
            entity.Property(e => e.Dimension1)
                .IsUnicode(false)
                .HasColumnName("dimension-1");
            entity.Property(e => e.Dimension2)
                .IsUnicode(false)
                .HasColumnName("dimension-2");
            entity.Property(e => e.Dimension3)
                .IsUnicode(false)
                .HasColumnName("dimension-3");
            entity.Property(e => e.Dimension4)
                .IsUnicode(false)
                .HasColumnName("dimension-4");
            entity.Property(e => e.Dimension5)
                .IsUnicode(false)
                .HasColumnName("dimension-5");
            entity.Property(e => e.DullScratchR).HasColumnName("dull scratch(r)");
            entity.Property(e => e.EdgeA1)
                .IsUnicode(false)
                .HasColumnName("edge-a1");
            entity.Property(e => e.EdgeA2)
                .IsUnicode(false)
                .HasColumnName("edge-a2");
            entity.Property(e => e.EdgeB1)
                .IsUnicode(false)
                .HasColumnName("edge-b1");
            entity.Property(e => e.EdgeB2)
                .IsUnicode(false)
                .HasColumnName("edge-b2");
            entity.Property(e => e.Flpflnm)
                .IsUnicode(false)
                .HasColumnName("flpflnm");
            entity.Property(e => e.FringeOverScrapped).HasColumnName("fringe over (scrapped)");
            entity.Property(e => e.Glasstype)
                .IsUnicode(false)
                .HasColumnName("glasstype");
            entity.Property(e => e.Good).HasColumnName("good");
            entity.Property(e => e.Handling).HasColumnName("handling");
            entity.Property(e => e.HandlingBeforeLoad).HasColumnName("handling before load");
            entity.Property(e => e.HdAg).HasColumnName("hd-ag");
            entity.Property(e => e.HdHw).HasColumnName("hd-hw");
            entity.Property(e => e.HdMc).HasColumnName("hd-mc");
            entity.Property(e => e.HdNr).HasColumnName("hd-nr");
            entity.Property(e => e.HdPost).HasColumnName("hd-post");
            entity.Property(e => e.HdTf).HasColumnName("hd-tf");
            entity.Property(e => e.HdTn).HasColumnName("hd-tn");
            entity.Property(e => e.Lost).HasColumnName("lost");
            entity.Property(e => e.Ltfmelt)
                .IsUnicode(false)
                .HasColumnName("ltfmelt");
            entity.Property(e => e.Ltinvst)
                .IsUnicode(false)
                .HasColumnName("ltinvst");
            entity.Property(e => e.Ltlotno)
                .IsUnicode(false)
                .HasColumnName("ltlotno");
            entity.Property(e => e.Ltoprid).HasColumnName("ltoprid");
            entity.Property(e => e.Lttmid1).HasColumnName("lttmid1");
            entity.Property(e => e.Lttyhis)
                .IsUnicode(false)
                .HasColumnName("lttyhis");
            entity.Property(e => e.McTime)
                .IsUnicode(false)
                .HasColumnName("mc (time)");
            entity.Property(e => e.Mfchpad)
                .IsUnicode(false)
                .HasColumnName("mfchpad");
            entity.Property(e => e.Mfcoatseq)
                .IsUnicode(false)
                .HasColumnName("mfcoatseq");
            entity.Property(e => e.Mfeqpid)
                .IsUnicode(false)
                .HasColumnName("mfeqpid");
            entity.Property(e => e.Mfinpqn).HasColumnName("mfinpqn");
            entity.Property(e => e.Mfinspe)
                .IsUnicode(false)
                .HasColumnName("mfinspe");
            entity.Property(e => e.Mflappad)
                .IsUnicode(false)
                .HasColumnName("mflappad");
            entity.Property(e => e.Mfmandt)
                .HasColumnType("datetime")
                .HasColumnName("mfmandt");
            entity.Property(e => e.Mfmanpd)
                .HasColumnType("datetime")
                .HasColumnName("mfmanpd");
            entity.Property(e => e.Mfmanty).HasColumnName("mfmanty");
            entity.Property(e => e.Mfmaotb).HasColumnName("mfmaotb");
            entity.Property(e => e.Mfmasrl).HasColumnName("mfmasrl");
            entity.Property(e => e.Mfoumid).HasColumnName("mfoumid");
            entity.Property(e => e.Mfoutav).HasColumnName("mfoutav");
            entity.Property(e => e.Mfoutho).HasColumnName("mfoutho");
            entity.Property(e => e.Mfoutqn).HasColumnName("mfoutqn");
            entity.Property(e => e.Mfpadse)
                .IsUnicode(false)
                .HasColumnName("mfpadse");
            entity.Property(e => e.Mfpidcus)
                .IsUnicode(false)
                .HasColumnName("mfpidcus");
            entity.Property(e => e.Mfpidgl)
                .IsUnicode(false)
                .HasColumnName("mfpidgl");
            entity.Property(e => e.Mfpidrev).HasColumnName("mfpidrev");
            entity.Property(e => e.Mfplpad)
                .IsUnicode(false)
                .HasColumnName("mfplpad");
            entity.Property(e => e.Mfprcid)
                .IsUnicode(false)
                .HasColumnName("mfprcid");
            entity.Property(e => e.Mfrjdes)
                .IsUnicode(false)
                .HasColumnName("mfrjdes");
            entity.Property(e => e.Mfrjqan).HasColumnName("mfrjqan");
            entity.Property(e => e.Mfshelf)
                .IsUnicode(false)
                .HasColumnName("mfshelf");
            entity.Property(e => e.Mfstcod)
                .IsUnicode(false)
                .HasColumnName("mfstcod");
            entity.Property(e => e.Mfstdet)
                .IsUnicode(false)
                .HasColumnName("mfstdet");
            entity.Property(e => e.NrOver).HasColumnName("nr over");
            entity.Property(e => e.OrangePeelH).HasColumnName("orange peel(h)");
            entity.Property(e => e.Other).HasColumnName("other");
            entity.Property(e => e.OtherH).HasColumnName("other(h)");
            entity.Property(e => e.PadLot)
                .IsUnicode(false)
                .HasColumnName("pad lot");
            entity.Property(e => e.PadTime)
                .IsUnicode(false)
                .HasColumnName("pad time");
            entity.Property(e => e.ParameterGa)
                .IsUnicode(false)
                .HasColumnName("parameter-ga");
            entity.Property(e => e.ParameterGb)
                .IsUnicode(false)
                .HasColumnName("parameter-gb");
            entity.Property(e => e.ParameterGc)
                .IsUnicode(false)
                .HasColumnName("parameter-gc");
            entity.Property(e => e.ParameterThk)
                .IsUnicode(false)
                .HasColumnName("parameter-thk");
            entity.Property(e => e.PolishZujiR).HasColumnName("polish zuji(r)");
            entity.Property(e => e.PolishingTime)
                .IsUnicode(false)
                .HasColumnName("polishing time");
            entity.Property(e => e.Sample).HasColumnName("sample");
            entity.Property(e => e.Scratch).HasColumnName("scratch");
            entity.Property(e => e.ScratchBeforeLoad).HasColumnName("scratch before load");
            entity.Property(e => e.Series1)
                .IsUnicode(false)
                .HasColumnName("series-1");
            entity.Property(e => e.Series2)
                .IsUnicode(false)
                .HasColumnName("series-2");
            entity.Property(e => e.Series3)
                .IsUnicode(false)
                .HasColumnName("series-3");
            entity.Property(e => e.Series4)
                .IsUnicode(false)
                .HasColumnName("series-4");
            entity.Property(e => e.Series5)
                .IsUnicode(false)
                .HasColumnName("series-5");
            entity.Property(e => e.SlurryTime)
                .IsUnicode(false)
                .HasColumnName("slurry time");
            entity.Property(e => e.SlurryTot)
                .IsUnicode(false)
                .HasColumnName("slurry tot");
            entity.Property(e => e.Stair1)
                .IsUnicode(false)
                .HasColumnName("stair1");
            entity.Property(e => e.Stair2)
                .IsUnicode(false)
                .HasColumnName("stair2");
            entity.Property(e => e.Stair3)
                .IsUnicode(false)
                .HasColumnName("stair3");
            entity.Property(e => e.Stair4)
                .IsUnicode(false)
                .HasColumnName("stair4");
            entity.Property(e => e.Stair5)
                .IsUnicode(false)
                .HasColumnName("stair5");
            entity.Property(e => e.Stair6)
                .IsUnicode(false)
                .HasColumnName("stair6");
            entity.Property(e => e.Stair7)
                .IsUnicode(false)
                .HasColumnName("stair7");
            entity.Property(e => e.TNLow).HasColumnName("t/n low");
            entity.Property(e => e.Thickness1)
                .IsUnicode(false)
                .HasColumnName("thickness-1");
            entity.Property(e => e.Thickness2)
                .IsUnicode(false)
                .HasColumnName("thickness-2");
            entity.Property(e => e.Thickness3)
                .IsUnicode(false)
                .HasColumnName("thickness-3");
            entity.Property(e => e.Thickness4)
                .IsUnicode(false)
                .HasColumnName("thickness-4");
            entity.Property(e => e.Thickness5)
                .IsUnicode(false)
                .HasColumnName("thickness-5");
            entity.Property(e => e.ThicknessOver).HasColumnName("thickness over");
            entity.Property(e => e.ThkAfter)
                .IsUnicode(false)
                .HasColumnName("thk after");
            entity.Property(e => e.ThkBefore)
                .IsUnicode(false)
                .HasColumnName("thk before");
            entity.Property(e => e.ThkDiffH).HasColumnName("thk diff(h)");
            entity.Property(e => e.WidthLenghtA1)
                .IsUnicode(false)
                .HasColumnName("width/lenght-a1");
            entity.Property(e => e.WidthLenghtA2)
                .IsUnicode(false)
                .HasColumnName("width/lenght-a2");
            entity.Property(e => e.WidthLenghtB1)
                .IsUnicode(false)
                .HasColumnName("width/lenght-b1");
            entity.Property(e => e.WidthLenghtB2)
                .IsUnicode(false)
                .HasColumnName("width/lenght-b2");
            entity.Property(e => e.Yield)
                .IsUnicode(false)
                .HasColumnName("yield");
        });

        modelBuilder.Entity<OutputDefectA0400Realtime>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("Output_Defect_A0400_realtime");

            entity.Property(e => e.Broken).HasColumnName("broken");
            entity.Property(e => e.BrokenBeforeLoad).HasColumnName("broken before load");
            entity.Property(e => e.BrokenH).HasColumnName("broken(h)");
            entity.Property(e => e.Chip).HasColumnName("chip");
            entity.Property(e => e.ChipBeforeLoad).HasColumnName("chip before load");
            entity.Property(e => e.Crack).HasColumnName("crack");
            entity.Property(e => e.CrackBeforeLoad).HasColumnName("crack before load");
            entity.Property(e => e.DataH).HasColumnName("data(h)");
            entity.Property(e => e.DullScratchR).HasColumnName("dull scratch(r)");
            entity.Property(e => e.Flpflnm)
                .IsUnicode(false)
                .HasColumnName("flpflnm");
            entity.Property(e => e.FringeOverScrapped).HasColumnName("fringe over (scrapped)");
            entity.Property(e => e.Glasstype)
                .IsUnicode(false)
                .HasColumnName("glasstype");
            entity.Property(e => e.Good).HasColumnName("good");
            entity.Property(e => e.Handling).HasColumnName("handling");
            entity.Property(e => e.HandlingBeforeLoad).HasColumnName("handling before load");
            entity.Property(e => e.HdAg).HasColumnName("hd-ag");
            entity.Property(e => e.HdHw).HasColumnName("hd-hw");
            entity.Property(e => e.HdMc).HasColumnName("hd-mc");
            entity.Property(e => e.HdNr).HasColumnName("hd-nr");
            entity.Property(e => e.HdPost).HasColumnName("hd-post");
            entity.Property(e => e.HdTf).HasColumnName("hd-tf");
            entity.Property(e => e.HdTn).HasColumnName("hd-tn");
            entity.Property(e => e.Lost).HasColumnName("lost");
            entity.Property(e => e.Ltfmelt)
                .IsUnicode(false)
                .HasColumnName("ltfmelt");
            entity.Property(e => e.Ltinvst)
                .IsUnicode(false)
                .HasColumnName("ltinvst");
            entity.Property(e => e.Ltlotno)
                .IsUnicode(false)
                .HasColumnName("ltlotno");
            entity.Property(e => e.Ltoprid).HasColumnName("ltoprid");
            entity.Property(e => e.Lttmid1).HasColumnName("lttmid1");
            entity.Property(e => e.Lttyhis)
                .IsUnicode(false)
                .HasColumnName("lttyhis");
            entity.Property(e => e.McTime)
                .IsUnicode(false)
                .HasColumnName("mc (time)");
            entity.Property(e => e.Mfchpad)
                .IsUnicode(false)
                .HasColumnName("mfchpad");
            entity.Property(e => e.Mfcoatseq)
                .IsUnicode(false)
                .HasColumnName("mfcoatseq");
            entity.Property(e => e.Mfeqpid)
                .IsUnicode(false)
                .HasColumnName("mfeqpid");
            entity.Property(e => e.Mfinpqn).HasColumnName("mfinpqn");
            entity.Property(e => e.Mfinspe)
                .IsUnicode(false)
                .HasColumnName("mfinspe");
            entity.Property(e => e.Mflappad)
                .IsUnicode(false)
                .HasColumnName("mflappad");
            entity.Property(e => e.Mfmandt)
                .HasColumnType("datetime")
                .HasColumnName("mfmandt");
            entity.Property(e => e.Mfmanpd)
                .HasColumnType("datetime")
                .HasColumnName("mfmanpd");
            entity.Property(e => e.Mfmanty).HasColumnName("mfmanty");
            entity.Property(e => e.Mfmaotb).HasColumnName("mfmaotb");
            entity.Property(e => e.Mfmasrl).HasColumnName("mfmasrl");
            entity.Property(e => e.Mfoumid).HasColumnName("mfoumid");
            entity.Property(e => e.Mfoutav).HasColumnName("mfoutav");
            entity.Property(e => e.Mfoutho).HasColumnName("mfoutho");
            entity.Property(e => e.Mfoutqn).HasColumnName("mfoutqn");
            entity.Property(e => e.Mfpadse)
                .IsUnicode(false)
                .HasColumnName("mfpadse");
            entity.Property(e => e.Mfpidcus)
                .IsUnicode(false)
                .HasColumnName("mfpidcus");
            entity.Property(e => e.Mfpidgl)
                .IsUnicode(false)
                .HasColumnName("mfpidgl");
            entity.Property(e => e.Mfpidrev).HasColumnName("mfpidrev");
            entity.Property(e => e.Mfplpad)
                .IsUnicode(false)
                .HasColumnName("mfplpad");
            entity.Property(e => e.Mfprcid)
                .IsUnicode(false)
                .HasColumnName("mfprcid");
            entity.Property(e => e.Mfrjdes)
                .IsUnicode(false)
                .HasColumnName("mfrjdes");
            entity.Property(e => e.Mfrjqan).HasColumnName("mfrjqan");
            entity.Property(e => e.Mfshelf)
                .IsUnicode(false)
                .HasColumnName("mfshelf");
            entity.Property(e => e.Mfstcod)
                .IsUnicode(false)
                .HasColumnName("mfstcod");
            entity.Property(e => e.Mfstdet)
                .IsUnicode(false)
                .HasColumnName("mfstdet");
            entity.Property(e => e.NrOver).HasColumnName("nr over");
            entity.Property(e => e.OrangePeelH).HasColumnName("orange peel(h)");
            entity.Property(e => e.Other).HasColumnName("other");
            entity.Property(e => e.OtherH).HasColumnName("other(h)");
            entity.Property(e => e.PolishZujiR).HasColumnName("polish zuji(r)");
            entity.Property(e => e.Sample).HasColumnName("sample");
            entity.Property(e => e.Scratch).HasColumnName("scratch");
            entity.Property(e => e.ScratchBeforeLoad).HasColumnName("scratch before load");
            entity.Property(e => e.TNLow).HasColumnName("t/n low");
            entity.Property(e => e.ThicknessOver).HasColumnName("thickness over");
            entity.Property(e => e.ThkDiffH).HasColumnName("thk diff(h)");
            entity.Property(e => e.Yield)
                .IsUnicode(false)
                .HasColumnName("yield");
        });

        modelBuilder.Entity<OutputDefectA0600>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("Output_Defect_A0600");

            entity.Property(e => e.Broken).HasColumnName("broken");
            entity.Property(e => e.BruiseScratch).HasColumnName("bruise scratch");
            entity.Property(e => e.BuiseScratchR).HasColumnName("buise scratch(r)");
            entity.Property(e => e.Chip).HasColumnName("chip");
            entity.Property(e => e.Cloudy).HasColumnName("cloudy");
            entity.Property(e => e.CloudyR).HasColumnName("cloudy(r)");
            entity.Property(e => e.Cord).HasColumnName("cord");
            entity.Property(e => e.Crack).HasColumnName("crack");
            entity.Property(e => e.DisCenter).HasColumnName("dis-center");
            entity.Property(e => e.DullScratch).HasColumnName("dull scratch");
            entity.Property(e => e.DullScratchR).HasColumnName("dull scratch(r)");
            entity.Property(e => e.Erosion).HasColumnName("erosion");
            entity.Property(e => e.FingerPrint).HasColumnName("finger print");
            entity.Property(e => e.FingerPrintR).HasColumnName("finger print(r)");
            entity.Property(e => e.Flpflnm)
                .IsUnicode(false)
                .HasColumnName("flpflnm");
            entity.Property(e => e.ForeignSubstance).HasColumnName("foreign substance");
            entity.Property(e => e.ForeignSubstanceR).HasColumnName("foreign substance(r)");
            entity.Property(e => e.FringeOverScrapped).HasColumnName("fringe over (scrapped)");
            entity.Property(e => e.Glasstype)
                .IsUnicode(false)
                .HasColumnName("glasstype");
            entity.Property(e => e.Good).HasColumnName("good");
            entity.Property(e => e.GoodRankA).HasColumnName("good rank a");
            entity.Property(e => e.GoodRankB).HasColumnName("good rank b");
            entity.Property(e => e.Handling).HasColumnName("handling");
            entity.Property(e => e.InclusionSeed).HasColumnName("inclusion/seed");
            entity.Property(e => e.LineScratch).HasColumnName("line scratch");
            entity.Property(e => e.LineScratchR).HasColumnName("line scratch(r)");
            entity.Property(e => e.Ltfmelt)
                .IsUnicode(false)
                .HasColumnName("ltfmelt");
            entity.Property(e => e.Ltinvst)
                .IsUnicode(false)
                .HasColumnName("ltinvst");
            entity.Property(e => e.Ltlotno)
                .IsUnicode(false)
                .HasColumnName("ltlotno");
            entity.Property(e => e.Ltoprid).HasColumnName("ltoprid");
            entity.Property(e => e.Lttmid1).HasColumnName("lttmid1");
            entity.Property(e => e.Lttyhis)
                .IsUnicode(false)
                .HasColumnName("lttyhis");
            entity.Property(e => e.McTime)
                .IsUnicode(false)
                .HasColumnName("mc (time)");
            entity.Property(e => e.MenareR).HasColumnName("menare(r)");
            entity.Property(e => e.Mfchpad)
                .IsUnicode(false)
                .HasColumnName("mfchpad");
            entity.Property(e => e.Mfcoatseq)
                .IsUnicode(false)
                .HasColumnName("mfcoatseq");
            entity.Property(e => e.Mfeqpid)
                .IsUnicode(false)
                .HasColumnName("mfeqpid");
            entity.Property(e => e.Mfinpqn).HasColumnName("mfinpqn");
            entity.Property(e => e.Mfinspe)
                .IsUnicode(false)
                .HasColumnName("mfinspe");
            entity.Property(e => e.Mflappad)
                .IsUnicode(false)
                .HasColumnName("mflappad");
            entity.Property(e => e.Mfmandt)
                .HasColumnType("datetime")
                .HasColumnName("mfmandt");
            entity.Property(e => e.Mfmanpd)
                .HasColumnType("datetime")
                .HasColumnName("mfmanpd");
            entity.Property(e => e.Mfmanty).HasColumnName("mfmanty");
            entity.Property(e => e.Mfmaotb).HasColumnName("mfmaotb");
            entity.Property(e => e.Mfmasrl).HasColumnName("mfmasrl");
            entity.Property(e => e.Mfoumid).HasColumnName("mfoumid");
            entity.Property(e => e.Mfoutav).HasColumnName("mfoutav");
            entity.Property(e => e.Mfoutho).HasColumnName("mfoutho");
            entity.Property(e => e.Mfoutqn).HasColumnName("mfoutqn");
            entity.Property(e => e.Mfpadse)
                .IsUnicode(false)
                .HasColumnName("mfpadse");
            entity.Property(e => e.Mfpidcus)
                .IsUnicode(false)
                .HasColumnName("mfpidcus");
            entity.Property(e => e.Mfpidgl)
                .IsUnicode(false)
                .HasColumnName("mfpidgl");
            entity.Property(e => e.Mfpidrev).HasColumnName("mfpidrev");
            entity.Property(e => e.Mfplpad)
                .IsUnicode(false)
                .HasColumnName("mfplpad");
            entity.Property(e => e.Mfprcid)
                .IsUnicode(false)
                .HasColumnName("mfprcid");
            entity.Property(e => e.Mfrjdes)
                .IsUnicode(false)
                .HasColumnName("mfrjdes");
            entity.Property(e => e.Mfrjqan).HasColumnName("mfrjqan");
            entity.Property(e => e.Mfshelf)
                .IsUnicode(false)
                .HasColumnName("mfshelf");
            entity.Property(e => e.Mfstcod)
                .IsUnicode(false)
                .HasColumnName("mfstcod");
            entity.Property(e => e.Mfstdet)
                .IsUnicode(false)
                .HasColumnName("mfstdet");
            entity.Property(e => e.MicroScratch).HasColumnName("micro scratch");
            entity.Property(e => e.MicroScratchR).HasColumnName("micro scratch(r)");
            entity.Property(e => e.Nc).HasColumnName("nc");
            entity.Property(e => e.NrOver).HasColumnName("nr over");
            entity.Property(e => e.OrangePeel).HasColumnName("orange peel");
            entity.Property(e => e.OrangePeelR).HasColumnName("orange peel(r)");
            entity.Property(e => e.Other).HasColumnName("other");
            entity.Property(e => e.PointScratch).HasColumnName("point scratch");
            entity.Property(e => e.PointScratchR).HasColumnName("point scratch(r)");
            entity.Property(e => e.PolishZuji).HasColumnName("polish zuji");
            entity.Property(e => e.PolishZujiR).HasColumnName("polish zuji(r)");
            entity.Property(e => e.RollOff).HasColumnName("roll off");
            entity.Property(e => e.RollOffR).HasColumnName("roll off(r)");
            entity.Property(e => e.Sample).HasColumnName("sample");
            entity.Property(e => e.Shimi).HasColumnName("shimi");
            entity.Property(e => e.ShimiR).HasColumnName("shimi(r)");
            entity.Property(e => e.SideStain).HasColumnName("side stain");
            entity.Property(e => e.SlurryStain).HasColumnName("slurry stain");
            entity.Property(e => e.SlurryStainR).HasColumnName("slurry stain(r)");
            entity.Property(e => e.Stain).HasColumnName("stain");
            entity.Property(e => e.StainR).HasColumnName("stain(r)");
            entity.Property(e => e.Suname).HasColumnName("suname");
            entity.Property(e => e.SunameR).HasColumnName("suname(r)");
            entity.Property(e => e.Ultrasonic).HasColumnName("ultrasonic");
            entity.Property(e => e.UltrasonicR).HasColumnName("ultrasonic(r)");
            entity.Property(e => e.UnPolish).HasColumnName("un-polish");
            entity.Property(e => e.UnPolishR).HasColumnName("un-polish(r)");
            entity.Property(e => e.Yield)
                .IsUnicode(false)
                .HasColumnName("yield");
        });

        modelBuilder.Entity<OutputDefectA0600Realtime>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("Output_Defect_A0600_realtime");

            entity.Property(e => e.Broken).HasColumnName("broken");
            entity.Property(e => e.BruiseScratch).HasColumnName("bruise scratch");
            entity.Property(e => e.BuiseScratchR).HasColumnName("buise scratch(r)");
            entity.Property(e => e.Chip).HasColumnName("chip");
            entity.Property(e => e.Cloudy).HasColumnName("cloudy");
            entity.Property(e => e.CloudyR).HasColumnName("cloudy(r)");
            entity.Property(e => e.Cord).HasColumnName("cord");
            entity.Property(e => e.Crack).HasColumnName("crack");
            entity.Property(e => e.DisCenter).HasColumnName("dis-center");
            entity.Property(e => e.DullScratch).HasColumnName("dull scratch");
            entity.Property(e => e.DullScratchR).HasColumnName("dull scratch(r)");
            entity.Property(e => e.Erosion).HasColumnName("erosion");
            entity.Property(e => e.FingerPrint).HasColumnName("finger print");
            entity.Property(e => e.FingerPrintR).HasColumnName("finger print(r)");
            entity.Property(e => e.Flpflnm)
                .IsUnicode(false)
                .HasColumnName("flpflnm");
            entity.Property(e => e.ForeignSubstance).HasColumnName("foreign substance");
            entity.Property(e => e.ForeignSubstanceR).HasColumnName("foreign substance(r)");
            entity.Property(e => e.FringeOverScrapped).HasColumnName("fringe over (scrapped)");
            entity.Property(e => e.Glasstype)
                .IsUnicode(false)
                .HasColumnName("glasstype");
            entity.Property(e => e.Good).HasColumnName("good");
            entity.Property(e => e.GoodRankA).HasColumnName("good rank a");
            entity.Property(e => e.GoodRankB).HasColumnName("good rank b");
            entity.Property(e => e.Handling).HasColumnName("handling");
            entity.Property(e => e.InclusionSeed).HasColumnName("inclusion/seed");
            entity.Property(e => e.LineScratch).HasColumnName("line scratch");
            entity.Property(e => e.LineScratchR).HasColumnName("line scratch(r)");
            entity.Property(e => e.Ltfmelt)
                .IsUnicode(false)
                .HasColumnName("ltfmelt");
            entity.Property(e => e.Ltinvst)
                .IsUnicode(false)
                .HasColumnName("ltinvst");
            entity.Property(e => e.Ltlotno)
                .IsUnicode(false)
                .HasColumnName("ltlotno");
            entity.Property(e => e.Ltoprid).HasColumnName("ltoprid");
            entity.Property(e => e.Lttmid1).HasColumnName("lttmid1");
            entity.Property(e => e.Lttyhis)
                .IsUnicode(false)
                .HasColumnName("lttyhis");
            entity.Property(e => e.McTime)
                .IsUnicode(false)
                .HasColumnName("mc (time)");
            entity.Property(e => e.MenareR).HasColumnName("menare(r)");
            entity.Property(e => e.Mfchpad)
                .IsUnicode(false)
                .HasColumnName("mfchpad");
            entity.Property(e => e.Mfcoatseq)
                .IsUnicode(false)
                .HasColumnName("mfcoatseq");
            entity.Property(e => e.Mfeqpid)
                .IsUnicode(false)
                .HasColumnName("mfeqpid");
            entity.Property(e => e.Mfinpqn).HasColumnName("mfinpqn");
            entity.Property(e => e.Mfinspe)
                .IsUnicode(false)
                .HasColumnName("mfinspe");
            entity.Property(e => e.Mflappad)
                .IsUnicode(false)
                .HasColumnName("mflappad");
            entity.Property(e => e.Mfmandt)
                .HasColumnType("datetime")
                .HasColumnName("mfmandt");
            entity.Property(e => e.Mfmanpd)
                .HasColumnType("datetime")
                .HasColumnName("mfmanpd");
            entity.Property(e => e.Mfmanty).HasColumnName("mfmanty");
            entity.Property(e => e.Mfmaotb).HasColumnName("mfmaotb");
            entity.Property(e => e.Mfmasrl).HasColumnName("mfmasrl");
            entity.Property(e => e.Mfoumid).HasColumnName("mfoumid");
            entity.Property(e => e.Mfoutav).HasColumnName("mfoutav");
            entity.Property(e => e.Mfoutho).HasColumnName("mfoutho");
            entity.Property(e => e.Mfoutqn).HasColumnName("mfoutqn");
            entity.Property(e => e.Mfpadse)
                .IsUnicode(false)
                .HasColumnName("mfpadse");
            entity.Property(e => e.Mfpidcus)
                .IsUnicode(false)
                .HasColumnName("mfpidcus");
            entity.Property(e => e.Mfpidgl)
                .IsUnicode(false)
                .HasColumnName("mfpidgl");
            entity.Property(e => e.Mfpidrev).HasColumnName("mfpidrev");
            entity.Property(e => e.Mfplpad)
                .IsUnicode(false)
                .HasColumnName("mfplpad");
            entity.Property(e => e.Mfprcid)
                .IsUnicode(false)
                .HasColumnName("mfprcid");
            entity.Property(e => e.Mfrjdes)
                .IsUnicode(false)
                .HasColumnName("mfrjdes");
            entity.Property(e => e.Mfrjqan).HasColumnName("mfrjqan");
            entity.Property(e => e.Mfshelf)
                .IsUnicode(false)
                .HasColumnName("mfshelf");
            entity.Property(e => e.Mfstcod)
                .IsUnicode(false)
                .HasColumnName("mfstcod");
            entity.Property(e => e.Mfstdet)
                .IsUnicode(false)
                .HasColumnName("mfstdet");
            entity.Property(e => e.MicroScratch).HasColumnName("micro scratch");
            entity.Property(e => e.MicroScratchR).HasColumnName("micro scratch(r)");
            entity.Property(e => e.Nc).HasColumnName("nc");
            entity.Property(e => e.NrOver).HasColumnName("nr over");
            entity.Property(e => e.OrangePeel).HasColumnName("orange peel");
            entity.Property(e => e.OrangePeelR).HasColumnName("orange peel(r)");
            entity.Property(e => e.Other).HasColumnName("other");
            entity.Property(e => e.PointScratch).HasColumnName("point scratch");
            entity.Property(e => e.PointScratchR).HasColumnName("point scratch(r)");
            entity.Property(e => e.PolishZuji).HasColumnName("polish zuji");
            entity.Property(e => e.PolishZujiR).HasColumnName("polish zuji(r)");
            entity.Property(e => e.RollOff).HasColumnName("roll off");
            entity.Property(e => e.RollOffR).HasColumnName("roll off(r)");
            entity.Property(e => e.Sample).HasColumnName("sample");
            entity.Property(e => e.Shimi).HasColumnName("shimi");
            entity.Property(e => e.ShimiR).HasColumnName("shimi(r)");
            entity.Property(e => e.SideStain).HasColumnName("side stain");
            entity.Property(e => e.SlurryStain).HasColumnName("slurry stain");
            entity.Property(e => e.SlurryStainR).HasColumnName("slurry stain(r)");
            entity.Property(e => e.Stain).HasColumnName("stain");
            entity.Property(e => e.StainR).HasColumnName("stain(r)");
            entity.Property(e => e.Suname).HasColumnName("suname");
            entity.Property(e => e.SunameR).HasColumnName("suname(r)");
            entity.Property(e => e.Ultrasonic).HasColumnName("ultrasonic");
            entity.Property(e => e.UltrasonicR).HasColumnName("ultrasonic(r)");
            entity.Property(e => e.UnPolish).HasColumnName("un-polish");
            entity.Property(e => e.UnPolishR).HasColumnName("un-polish(r)");
            entity.Property(e => e.Yield)
                .IsUnicode(false)
                .HasColumnName("yield");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}