// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SI24004.Models.SqlServer1;

public partial class OutputDefectA0600Realtime
{
    public long? Mfmasrl { get; set; }

    public string Ltlotno { get; set; }

    public long? Mfpidrev { get; set; }

    public string Mfprcid { get; set; }

    public long? Mfinpqn { get; set; }

    public long? Mfoutqn { get; set; }

    public long? Mfoutav { get; set; }

    public long? Mfoutho { get; set; }

    public long? Mfrjqan { get; set; }

    public string Mfrjdes { get; set; }

    public string Yield { get; set; }

    public DateTime? Mfmandt { get; set; }

    public DateTime? Mfmanpd { get; set; }

    public string Glasstype { get; set; }

    public string Mfpidcus { get; set; }

    public string Mfpidgl { get; set; }

    public string Ltinvst { get; set; }

    public string Mfeqpid { get; set; }

    public string McTime { get; set; }

    public string Mfpadse { get; set; }

    public string Mfshelf { get; set; }

    public string Mfinspe { get; set; }

    public string Ltfmelt { get; set; }

    public long? Mfmanty { get; set; }

    public long? Ltoprid { get; set; }

    public string Mfchpad { get; set; }

    public string Mflappad { get; set; }

    public string Mfplpad { get; set; }

    public string Mfcoatseq { get; set; }

    public string Lttyhis { get; set; }

    public string Mfstcod { get; set; }

    public string Mfstdet { get; set; }

    public long? Mfmaotb { get; set; }

    public long? Lttmid1 { get; set; }

    public string Flpflnm { get; set; }

    public long? Mfoumid { get; set; }

    public long? Good { get; set; }

    public long? Crack { get; set; }

    public long? Broken { get; set; }

    public long? Other { get; set; }

    public long? Chip { get; set; }

    public long? Sample { get; set; }

    public long? Handling { get; set; }

    public long? DisCenter { get; set; }

    public long? LineScratch { get; set; }

    public long? PointScratch { get; set; }

    public long? MicroScratch { get; set; }

    public long? Stain { get; set; }

    public long? SlurryStain { get; set; }

    public long? SideStain { get; set; }

    public long? ForeignSubstance { get; set; }

    public long? FingerPrint { get; set; }

    public long? PolishZuji { get; set; }

    public long? OrangePeel { get; set; }

    public long? RollOff { get; set; }

    public long? Suname { get; set; }

    public long? Shimi { get; set; }

    public long? UnPolish { get; set; }

    public long? Cloudy { get; set; }

    public long? Ultrasonic { get; set; }

    public long? Cord { get; set; }

    public long? InclusionSeed { get; set; }

    public long? Erosion { get; set; }

    public long? Nc { get; set; }

    public long? LineScratchR { get; set; }

    public long? PointScratchR { get; set; }

    public long? MicroScratchR { get; set; }

    public long? StainR { get; set; }

    public long? SlurryStainR { get; set; }

    public long? ForeignSubstanceR { get; set; }

    public long? FingerPrintR { get; set; }

    public long? PolishZujiR { get; set; }

    public long? OrangePeelR { get; set; }

    public long? RollOffR { get; set; }

    public long? SunameR { get; set; }

    public long? ShimiR { get; set; }

    public long? UnPolishR { get; set; }

    public long? CloudyR { get; set; }

    public long? MenareR { get; set; }

    public long? UltrasonicR { get; set; }

    public long? BruiseScratch { get; set; }

    public long? GoodRankA { get; set; }

    public long? GoodRankB { get; set; }

    public long? FringeOverScrapped { get; set; }

    public long? NrOver { get; set; }

    public long? DullScratch { get; set; }

    public long? DullScratchR { get; set; }

    public long? BuiseScratchR { get; set; }
}