// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SI24004.Models.SqlServer;

public partial class Th100Record
{
    public int LotId { get; set; }

    public string LotPo { get; set; }

    public string McPo { get; set; }

    public string NoPo { get; set; }

    public string MemberId { get; set; }

    public string Status { get; set; }

    public DateTime DateProcess { get; set; }

    public DateTime TimeProcess { get; set; }

    public string Th01 { get; set; }

    public string Th02 { get; set; }

    public string Th03 { get; set; }

    public string Th04 { get; set; }

    public string Th05 { get; set; }

    public string Th06 { get; set; }

    public string Th07 { get; set; }

    public string Th08 { get; set; }

    public string Th09 { get; set; }

    public string Th10 { get; set; }

    public string Th11 { get; set; }

    public string Th12 { get; set; }

    public string Th13 { get; set; }

    public string Th14 { get; set; }

    public string Th15 { get; set; }

    public string Th16 { get; set; }

    public string Th17 { get; set; }

    public string Th18 { get; set; }

    public string Th19 { get; set; }

    public string Th20 { get; set; }

    public string Th21 { get; set; }

    public string Th22 { get; set; }

    public string Th23 { get; set; }

    public string Th24 { get; set; }

    public string Th25 { get; set; }

    public string Th26 { get; set; }

    public string Th27 { get; set; }

    public string Th28 { get; set; }

    public string Th29 { get; set; }

    public string Th30 { get; set; }

    public string Th31 { get; set; }

    public string Th32 { get; set; }

    public string Th33 { get; set; }

    public string Th34 { get; set; }

    public string Th35 { get; set; }

    public string Th36 { get; set; }

    public string Th37 { get; set; }

    public string Th38 { get; set; }

    public string Th39 { get; set; }

    public string Th40 { get; set; }

    public string Th41 { get; set; }

    public string Th42 { get; set; }

    public string Th43 { get; set; }

    public string Th44 { get; set; }

    public string Th45 { get; set; }

    public string Th46 { get; set; }

    public string Th47 { get; set; }

    public string Th48 { get; set; }

    public string Th49 { get; set; }

    public string Th50 { get; set; }

    public string Th51 { get; set; }

    public string Th52 { get; set; }

    public string Th53 { get; set; }

    public string Th54 { get; set; }

    public string Th55 { get; set; }

    public string Th56 { get; set; }

    public string Th57 { get; set; }

    public string Th58 { get; set; }

    public string Th59 { get; set; }

    public string Th60 { get; set; }

    public string Th61 { get; set; }

    public string Th62 { get; set; }

    public string Th63 { get; set; }

    public string Th64 { get; set; }

    public string Th65 { get; set; }

    public string Th66 { get; set; }

    public string Th67 { get; set; }

    public string Th68 { get; set; }

    public string Th69 { get; set; }

    public string Th70 { get; set; }

    public string Th71 { get; set; }

    public string Th72 { get; set; }

    public string Th73 { get; set; }

    public string Th74 { get; set; }

    public string Th75 { get; set; }

    public string Th76 { get; set; }

    public string Th77 { get; set; }

    public string Th78 { get; set; }

    public string Th79 { get; set; }

    public string Th80 { get; set; }

    public string Th81 { get; set; }

    public string Th82 { get; set; }

    public string Th83 { get; set; }

    public string Th84 { get; set; }

    public string Th85 { get; set; }

    public string Th86 { get; set; }

    public string Th87 { get; set; }

    public string Th88 { get; set; }

    public string Th89 { get; set; }

    public string Th90 { get; set; }

    public string Th91 { get; set; }

    public string Th92 { get; set; }

    public string Th93 { get; set; }

    public string Th94 { get; set; }

    public string Th95 { get; set; }

    public string Th96 { get; set; }

    public string Th97 { get; set; }

    public string Th98 { get; set; }

    public string Th99 { get; set; }

    public string Th100 { get; set; }

    public string Th101 { get; set; }

    public string Th102 { get; set; }

    public string Th103 { get; set; }

    public string Th104 { get; set; }

    public string Th105 { get; set; }

    public string Th106 { get; set; }

    public string Th107 { get; set; }

    public string Th108 { get; set; }

    public string Th109 { get; set; }

    public string Th110 { get; set; }

    public string Th111 { get; set; }

    public string Th112 { get; set; }

    public string Th113 { get; set; }

    public string Th114 { get; set; }

    public string Th115 { get; set; }

    public string Th116 { get; set; }

    public string Th117 { get; set; }

    public string Th118 { get; set; }

    public string Th119 { get; set; }

    public string Th120 { get; set; }

    public string Th121 { get; set; }

    public string Th122 { get; set; }

    public string Th123 { get; set; }

    public string Th124 { get; set; }

    public string Th125 { get; set; }

    public string Th126 { get; set; }

    public string Th127 { get; set; }

    public string Th128 { get; set; }

    public string Th129 { get; set; }

    public string Th130 { get; set; }

    public string Th131 { get; set; }

    public string Th132 { get; set; }

    public string Th133 { get; set; }

    public string Th134 { get; set; }

    public string Th135 { get; set; }

    public string Th136 { get; set; }

    public string Th137 { get; set; }

    public string Th138 { get; set; }

    public string Th139 { get; set; }

    public string Th140 { get; set; }

    public string Th141 { get; set; }

    public string Th142 { get; set; }

    public string Th143 { get; set; }

    public string Th144 { get; set; }

    public string Th145 { get; set; }

    public string Th146 { get; set; }

    public string Th147 { get; set; }

    public string Th148 { get; set; }

    public string Th149 { get; set; }

    public string Th150 { get; set; }

    public string Th151 { get; set; }

    public string Th152 { get; set; }

    public string Th153 { get; set; }

    public string Th154 { get; set; }

    public string Th155 { get; set; }

    public string Th156 { get; set; }

    public string Th157 { get; set; }

    public string Th158 { get; set; }

    public string Th159 { get; set; }

    public string Th160 { get; set; }

    public string Th161 { get; set; }

    public string Th162 { get; set; }

    public string Th163 { get; set; }

    public string Th164 { get; set; }

    public string Th165 { get; set; }

    public string Th166 { get; set; }

    public string Th167 { get; set; }

    public string Th168 { get; set; }

    public string Th169 { get; set; }

    public string Th170 { get; set; }

    public string Th171 { get; set; }

    public string Th172 { get; set; }

    public string Th173 { get; set; }

    public string Th174 { get; set; }

    public string Th175 { get; set; }

    public string Th176 { get; set; }

    public string Th177 { get; set; }

    public string Th178 { get; set; }

    public string Th179 { get; set; }

    public string Th180 { get; set; }

    public string Th181 { get; set; }

    public string Th182 { get; set; }

    public string Th183 { get; set; }

    public string Th184 { get; set; }

    public string Th185 { get; set; }

    public string Th186 { get; set; }

    public string Th187 { get; set; }

    public string Th188 { get; set; }

    public string Th189 { get; set; }

    public string Th190 { get; set; }

    public string Th191 { get; set; }

    public string Th192 { get; set; }

    public string Th193 { get; set; }

    public string Th194 { get; set; }

    public string Th195 { get; set; }

    public string Th196 { get; set; }

    public string Th197 { get; set; }

    public string Th198 { get; set; }

    public string Th199 { get; set; }

    public string Th200 { get; set; }

    public string Th201 { get; set; }

    public string Th202 { get; set; }

    public string Th203 { get; set; }

    public string Th204 { get; set; }

    public string Th205 { get; set; }

    public string Th206 { get; set; }

    public string Th207 { get; set; }

    public string Th208 { get; set; }

    public string Th209 { get; set; }

    public string Th210 { get; set; }

    public string Th211 { get; set; }

    public string Th212 { get; set; }

    public string Th213 { get; set; }

    public string Th214 { get; set; }

    public string Th215 { get; set; }

    public string Th216 { get; set; }

    public string Th217 { get; set; }

    public string Th218 { get; set; }

    public string Th219 { get; set; }

    public string Th220 { get; set; }

    public string Th221 { get; set; }

    public string Th222 { get; set; }

    public string Th223 { get; set; }

    public string Th224 { get; set; }

    public string Th225 { get; set; }

    public string Th226 { get; set; }

    public string Th227 { get; set; }

    public string Th228 { get; set; }

    public string Th229 { get; set; }

    public string Th230 { get; set; }

    public string Th231 { get; set; }

    public string Th232 { get; set; }

    public string Th233 { get; set; }

    public string Th234 { get; set; }

    public string Th235 { get; set; }

    public string Th236 { get; set; }

    public string Th237 { get; set; }

    public string Th238 { get; set; }

    public string Th239 { get; set; }

    public string Th240 { get; set; }

    public string Th241 { get; set; }

    public string Th242 { get; set; }

    public string Th243 { get; set; }

    public string Th244 { get; set; }

    public string Th245 { get; set; }

    public string Th246 { get; set; }

    public string Th247 { get; set; }

    public string Th248 { get; set; }

    public string Th249 { get; set; }

    public string Th250 { get; set; }

    public string ImobileLot { get; set; }

    public string ImobileType { get; set; }

    public string ImobileSize { get; set; }

    public string McType { get; set; }

    public string Process { get; set; }

    public string Th251 { get; set; }

    public string Th252 { get; set; }

    public string Th253 { get; set; }

    public string Th254 { get; set; }

    public string Th255 { get; set; }

    public string Th256 { get; set; }

    public string Th257 { get; set; }

    public string Th258 { get; set; }

    public string Th259 { get; set; }

    public string Th260 { get; set; }

    public string Th261 { get; set; }

    public string Th262 { get; set; }

    public string Th263 { get; set; }

    public string Th264 { get; set; }

    public string Th265 { get; set; }

    public string Th266 { get; set; }

    public string Th267 { get; set; }

    public string Th268 { get; set; }

    public string Th269 { get; set; }

    public string Th270 { get; set; }

    public string Th271 { get; set; }

    public string Th272 { get; set; }

    public string Th273 { get; set; }

    public string Th274 { get; set; }

    public string Th275 { get; set; }

    public string Th276 { get; set; }

    public string Th277 { get; set; }

    public string Th278 { get; set; }

    public string Th279 { get; set; }

    public string Th280 { get; set; }

    public string Th281 { get; set; }

    public string Th282 { get; set; }

    public string Th283 { get; set; }

    public string Th284 { get; set; }

    public string Th285 { get; set; }

    public string Th286 { get; set; }

    public string Th287 { get; set; }

    public string Th288 { get; set; }

    public string Th289 { get; set; }

    public string Th290 { get; set; }

    public string Th291 { get; set; }

    public string Th292 { get; set; }

    public string Th293 { get; set; }

    public string Th294 { get; set; }

    public string Th295 { get; set; }

    public string Th296 { get; set; }

    public string Th297 { get; set; }

    public string Th298 { get; set; }

    public string Th299 { get; set; }

    public string Th300 { get; set; }

    public string Hostname { get; set; }

    public string Ipaddress { get; set; }

    public string LaserMc { get; set; }
}