// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SI24004.Models.MySQL;

public partial class CurrencyRate
{
    public long CurId { get; set; }

    public DateTime? CurDate { get; set; }

    public string CurCode { get; set; }

    public decimal? CurTts { get; set; }

    public decimal? CurTtb { get; set; }

    public string CurSource { get; set; }

    public string CurDescription { get; set; }

    public DateTime? CurUpdate { get; set; }

    public int? UserId { get; set; }

    public string UserName { get; set; }
}