// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SI24004.Models.MySQL;

public partial class ItemBomStock
{
    public int StockId { get; set; }

    public int? StockBomId { get; set; }

    public int? StockItemId { get; set; }

    public string Stock01 { get; set; }

    public string Stock02 { get; set; }

    public string Stock03 { get; set; }

    public string Stock04 { get; set; }

    public string Stock05 { get; set; }

    public string Stock06 { get; set; }

    public string Stock07 { get; set; }

    public string Stock08 { get; set; }

    public string Stock09 { get; set; }

    public string Stock10 { get; set; }

    public string Stock11 { get; set; }

    public string Stock12 { get; set; }

    public string StockYear { get; set; }
}