// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SI24004.Models.MySQL;

public partial class ItemBomOut
{
    public int OutId { get; set; }

    public string OutItem { get; set; }

    public DateOnly? OutDate { get; set; }

    public string OutQty { get; set; }
}