// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SI24004.Models.MySQL;

public partial class ItemBomList
{
    public int BomId { get; set; }

    public int BomList { get; set; }

    public string BomSection { get; set; }

    public int BomItemId { get; set; }

    public string BomMainUsage { get; set; }

    public string BomUsage { get; set; }

    public string BomYield { get; set; }

    public string BomRemain { get; set; }

    public int BomActive { get; set; }
}