// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SI24004.Models.MySQL;

public partial class ReceiveMonth
{
    public int? ItemCardNo { get; set; }

    public DateOnly? CardDate { get; set; }

    public string PoNo { get; set; }

    public string InvNo { get; set; }

    public string ItemCode { get; set; }

    public string ItemName { get; set; }

    public string ItemDescription { get; set; }

    public string ReceiveLotNo { get; set; }

    public decimal? InQuantity { get; set; }

    public string ItemCurrency { get; set; }

    public decimal? ItemPrice { get; set; }

    public decimal? ItemAmount { get; set; }

    public DateOnly? ExpireDate { get; set; }

    public string ContactName { get; set; }
}