// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SI24004.Models.MySQL;

public partial class WhPath
{
    public string PathName { get; set; }

    public int? Active { get; set; }
}