// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SI24004.Models.MySQL;

public partial class WhType
{
    public int TypeId { get; set; }

    public string TypeNameTh { get; set; }

    public string TypeNameEn { get; set; }

    public int? TypeStatus { get; set; }
}