// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SI24004.Models.MySQL;

public partial class ZVendor
{
    public int VId { get; set; }

    public string VDateShip { get; set; }

    public string VDateInsp { get; set; }

    public string VShipLot { get; set; }

    public string VUvirLot { get; set; }

    public string VPackLot1 { get; set; }

    public string VPackLot2 { get; set; }

    public string VPackLot3 { get; set; }

    public string VPackLot4 { get; set; }

    public string VPackLot5 { get; set; }

    public string VPackLot6 { get; set; }

    public int? VInput { get; set; }

    public int? VOutput { get; set; }

    public int? VSt1 { get; set; }

    public int? VSt2 { get; set; }

    public int? VSt3 { get; set; }

    public int? VSt4 { get; set; }

    public int? VSt5 { get; set; }

    public int? VSt6 { get; set; }

    public int? VSt7 { get; set; }

    public string VProduct { get; set; }
}