// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SI24004.Models.MySQL;

public partial class IssueConfirm
{
    public int SqId { get; set; }

    public string SlipId { get; set; }

    public int? CardNo { get; set; }

    public string ItemCode { get; set; }

    public string InvNo { get; set; }

    public string LotNo { get; set; }

    public DateOnly? ExpireDate { get; set; }

    public int QrInput { get; set; }

    public int QrOutput { get; set; }

    public int SlipStatus { get; set; }
}