// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SI24004.Models.MySQL;

public partial class ItemLife
{
    public int ItemId { get; set; }

    public string ItemCode { get; set; }

    public string Description { get; set; }

    public string Expire { get; set; }

    public string RefFormat { get; set; }

    public string RefDescription { get; set; }

    public string RefWarning { get; set; }

    public string RefSignal { get; set; }

    public string RefKeep { get; set; }

    public string RefProtect { get; set; }

    public string RefControl { get; set; }
}