// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SI24004.Models.MySQL;

public partial class StockShelf
{
    public int Id { get; set; }

    public int? CardId { get; set; }

    public int? WhId { get; set; }

    public string Fact { get; set; }

    public int? ItemId { get; set; }

    public int? SlipId { get; set; }

    public string ShelfHold { get; set; }

    public string ShelfNo { get; set; }

    public string ShelfQty { get; set; }
}