// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SI24004.Models.MySQL;

public partial class UpdateOut
{
    public int? ItemId { get; set; }

    public DateOnly? CardDate { get; set; }

    public string ItemCode { get; set; }

    public decimal? Qty { get; set; }
}