// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SI24004.Models.MySQL;

public partial class WhPurpose
{
    public int PurposeId { get; set; }

    public string PurposeNameTh { get; set; }

    public string PurposeNameEn { get; set; }

    public int? PurposeStatus { get; set; }
}