// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SI24004.Models.Special;

public partial class UvirRankInvoice
{
    public string VProduct { get; set; }

    public string VUvirLot { get; set; }

    public int? VSt1 { get; set; }

    public int? VSt2 { get; set; }

    public int? VSt3 { get; set; }

    public int? VSt4 { get; set; }

    public int? VSt5 { get; set; }

    public int? VSt6 { get; set; }

    public int? VSt7 { get; set; }

    public int? VOutput { get; set; }

    public string VRank { get; set; }

    public string VPallet { get; set; }

    public string VShipLot { get; set; }

    public string VPosite { get; set; }

    public string Amgt { get; set; }
}