version: '3.9'

services:
  dotnet-app:
    container_name: dotnet-app
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    network_mode: host
    
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8083
    
    volumes:
      - ./publish:/app                   
      - ./logs:/app/logs                 
      - ./data:/app/data                  
    
    working_dir: /app
    command: dotnet SI24004.dll
    
    restart: unless-stopped
