// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SI24004.Models.SqlServer;

public partial class ThRecord
{
    public int LotId { get; set; }

    public string LotPo { get; set; }

    public string McPo { get; set; }

    public string NoPo { get; set; }

    public string MemberId { get; set; }

    public string Status { get; set; }

    public DateTime DateProcess { get; set; }

    public DateTime TimeProcess { get; set; }

    public string ThBefore { get; set; }

    public string AvgTh { get; set; }

    public string ProcessTime { get; set; }

    public string PoRate { get; set; }

    public string ThDif { get; set; }

    public string Margin { get; set; }

    public string Result { get; set; }

    public string Remark { get; set; }

    public string ImobileLot { get; set; }

    public string ImobileType { get; set; }

    public string ImobileSize { get; set; }

    public string McType { get; set; }

    public string Process { get; set; }

    public string Ca1In1 { get; set; }

    public string Ca1In2 { get; set; }

    public string Ca1In3 { get; set; }

    public string Ca1In4 { get; set; }

    public string Ca1In5 { get; set; }

    public string Ca1Out1 { get; set; }

    public string Ca1Out2 { get; set; }

    public string Ca1Out3 { get; set; }

    public string Ca1Out4 { get; set; }

    public string Ca1Out5 { get; set; }

    public string Ca2In1 { get; set; }

    public string Ca2In2 { get; set; }

    public string Ca2In3 { get; set; }

    public string Ca2In4 { get; set; }

    public string Ca2In5 { get; set; }

    public string Ca2Out1 { get; set; }

    public string Ca2Out2 { get; set; }

    public string Ca2Out3 { get; set; }

    public string Ca2Out4 { get; set; }

    public string Ca2Out5 { get; set; }

    public string Ca3In1 { get; set; }

    public string Ca3In2 { get; set; }

    public string Ca3In3 { get; set; }

    public string Ca3In4 { get; set; }

    public string Ca3In5 { get; set; }

    public string Ca3Out1 { get; set; }

    public string Ca3Out2 { get; set; }

    public string Ca3Out3 { get; set; }

    public string Ca3Out4 { get; set; }

    public string Ca3Out5 { get; set; }

    public string Ca4In1 { get; set; }

    public string Ca4In2 { get; set; }

    public string Ca4In3 { get; set; }

    public string Ca4In4 { get; set; }

    public string Ca4In5 { get; set; }

    public string Ca4Out1 { get; set; }

    public string Ca4Out2 { get; set; }

    public string Ca4Out3 { get; set; }

    public string Ca4Out4 { get; set; }

    public string Ca4Out5 { get; set; }

    public string Ca5In1 { get; set; }

    public string Ca5In2 { get; set; }

    public string Ca5In3 { get; set; }

    public string Ca5In4 { get; set; }

    public string Ca5In5 { get; set; }

    public string Ca5Out1 { get; set; }

    public string Ca5Out2 { get; set; }

    public string Ca5Out3 { get; set; }

    public string Ca5Out4 { get; set; }

    public string Ca5Out5 { get; set; }

    public string ThCin { get; set; }

    public string ThCout1 { get; set; }

    public string ThCout2 { get; set; }

    public string ThCout3 { get; set; }

    public string ThCout4 { get; set; }

    public string ThCout5 { get; set; }

    public string Hostname { get; set; }

    public string Ipaddress { get; set; }

    public string LaserMc { get; set; }

    public int? ProcessStep { get; set; }

    public string Ca1In6 { get; set; }

    public string Ca1In7 { get; set; }

    public string Ca1In8 { get; set; }

    public string Ca1In9 { get; set; }

    public string Ca1In10 { get; set; }

    public string Ca1Out6 { get; set; }

    public string Ca1Out7 { get; set; }

    public string Ca1Out8 { get; set; }

    public string Ca1Out9 { get; set; }

    public string Ca1Out10 { get; set; }

    public string Ca2In6 { get; set; }

    public string Ca2In7 { get; set; }

    public string Ca3In6 { get; set; }

    public string Ca3In7 { get; set; }

    public string Ca4In6 { get; set; }

    public string Ca4In7 { get; set; }

    public string Ca5In6 { get; set; }

    public string Ca5In7 { get; set; }

    public string ThCin2 { get; set; }

    public string ThCin3 { get; set; }

    public string ThCin4 { get; set; }

    public string ThCin5 { get; set; }

    public string Ca2In8 { get; set; }

    public string Ca2In9 { get; set; }

    public string Ca2In10 { get; set; }

    public string Ca3In8 { get; set; }

    public string Ca3In9 { get; set; }

    public string Ca3In10 { get; set; }

    public string Ca4In8 { get; set; }

    public string Ca4In9 { get; set; }

    public string Ca4In10 { get; set; }

    public string Ca5In8 { get; set; }

    public string Ca5In9 { get; set; }

    public string Ca5In10 { get; set; }

    public string Program { get; set; }
}