import type { ThemeDefinition } from 'vuetify'

export const staticPrimaryColor = '#3b82f6'
export const staticPrimaryDarkenColor = '#2563eb'

export const themes: Record<string, ThemeDefinition> = {
  light: {
    dark: false,
    colors: {
      'primary': staticPrimaryColor,
      'on-primary': '#fff',
      'primary-darken-1': staticPrimaryDarkenColor,
      'secondary': '#64748b',
      'on-secondary': '#fff',
      'secondary-darken-1': '#475569',
      'success': '#16a34a',
      'on-success': '#fff',
      'success-darken-1': '#15803d',
      'info': '#0891b2',
      'on-info': '#fff',
      'info-darken-1': '#0e7490',
      'warning': '#d97706',
      'on-warning': '#fff',
      'warning-darken-1': '#b45309',
      'error': '#dc2626',
      'on-error': '#fff',
      'error-darken-1': '#b91c1c',
      'background': '#f8fafc',
      'on-background': '#0f172a',
      'surface': '#ffffff',
      'on-surface': '#0f172a',
      'grey-50': '#f8fafc',
      'grey-100': '#f1f5f9',
      'grey-200': '#e2e8f0',
      'grey-300': '#cbd5e1',
      'grey-400': '#94a3b8',
      'grey-500': '#64748b',
      'grey-600': '#475569',
      'grey-700': '#334155',
      'grey-800': '#1e293b',
      'grey-900': '#0f172a',
      'grey-light': '#f8fafc',
      'perfect-scrollbar-thumb': '#cbd5e1',
      'skin-bordered-background': '#fff',
      'skin-bordered-surface': '#fff',
      'expansion-panel-text-custom-bg': '#f8fafc',
    },

    variables: {
      'code-color': '#8b5cf6',
      'overlay-scrim-background': '#0f172a',
      'tooltip-background': '#1e293b',
      'overlay-scrim-opacity': 0.45,
      'hover-opacity': 0.05,
      'focus-opacity': 0.08,
      'selected-opacity': 0.08,
      'activated-opacity': 0.12,
      'pressed-opacity': 0.12,
      'dragged-opacity': 0.08,
      'disabled-opacity': 0.4,
      'border-color': '#2F2B3D',
      'border-opacity': 0.12,
      'table-header-color': '#EAEAEC',
      'high-emphasis-opacity': 0.9,
      'medium-emphasis-opacity': 0.7,
      'switch-opacity': 0.2,
      'switch-disabled-track-opacity': 0.3,
      'switch-disabled-thumb-opacity': 0.4,
      'switch-checked-disabled-opacity': 0.3,
      'track-bg': '#F1F0F2',

      // Shadows
      'shadow-key-umbra-color': '#2F2B3D',
      'shadow-xs-opacity': 0.10,
      'shadow-sm-opacity': 0.12,
      'shadow-md-opacity': 0.14,
      'shadow-lg-opacity': 0.16,
      'shadow-xl-opacity': 0.18,
    },
  },
  dark: {
    dark: true,
    colors: {
      'primary': staticPrimaryColor,
      'on-primary': '#fff',
      'primary-darken-1': staticPrimaryDarkenColor,
      'secondary': '#94a3b8',
      'on-secondary': '#fff',
      'secondary-darken-1': '#64748b',
      'success': '#22c55e',
      'on-success': '#fff',
      'success-darken-1': '#16a34a',
      'info': '#22d3ee',
      'on-info': '#0f172a',
      'info-darken-1': '#0891b2',
      'warning': '#fbbf24',
      'on-warning': '#0f172a',
      'warning-darken-1': '#d97706',
      'error': '#f87171',
      'on-error': '#fff',
      'error-darken-1': '#dc2626',
      'background': '#0f172a',
      'on-background': '#e2e8f0',
      'surface': '#1e293b',
      'on-surface': '#e2e8f0',
      'grey-50': '#1e293b',
      'grey-100': '#334155',
      'grey-200': '#1e293b',
      'grey-300': '#475569',
      'grey-400': '#64748b',
      'grey-500': '#94a3b8',
      'grey-600': '#cbd5e1',
      'grey-700': '#e2e8f0',
      'grey-800': '#f1f5f9',
      'grey-900': '#f8fafc',
      'grey-light': '#334155',
      'perfect-scrollbar-thumb': '#475569',
      'skin-bordered-background': '#1e293b',
      'skin-bordered-surface': '#1e293b',
    },
    variables: {
      'code-color': '#a78bfa',
      'overlay-scrim-background': '#0f172a',
      'tooltip-background': '#e2e8f0',
      'overlay-scrim-opacity': 0.6,
      'hover-opacity': 0.05,
      'focus-opacity': 0.08,
      'selected-opacity': 0.08,
      'activated-opacity': 0.12,
      'pressed-opacity': 0.12,
      'dragged-opacity': 0.08,
      'disabled-opacity': 0.4,
      'border-color': '#e2e8f0',
      'border-opacity': 0.12,
      'table-header-color': '#334155',
      'high-emphasis-opacity': 0.9,
      'medium-emphasis-opacity': 0.65,
      'switch-opacity': 0.4,
      'switch-disabled-track-opacity': 0.4,
      'switch-disabled-thumb-opacity': 0.8,
      'switch-checked-disabled-opacity': 0.3,
      'track-bg': '#3A3F57',

      // Shadows
      'shadow-key-umbra-color': '#131120',
      'shadow-xs-opacity': 0.16,
      'shadow-sm-opacity': 0.18,
      'shadow-md-opacity': 0.2,
      'shadow-lg-opacity': 0.22,
      'shadow-xl-opacity': 0.24,
    },
  },
}

export default themes
